package l2s.gameserver.templates.item;

public enum ExItemType
{
	NONE_0(-1),

	
	SWORD(0), 
	MAGIC_SWORD(0), 
	DAGGER(0), 
	RAPIER(0), 
	BIG_SWORD(0), 
	ANCIENT_SWORD(0), 
	DUAL_SWORD(0), 
	DUAL_DAGGER(0), 
	BLUNT_WEAPON(0), 
	MAGIC_BLUNT_WEAPON(0), 
	BIG_BLUNT_WEAPON(0), 
	BIG_MAGIC_BLUNT_WEAPON(0), 
	DUAL_BLUNT_WEAPON(0), 
	BOW(0), 
	CROSSBOW(0), 
	HAND_TO_HAND(0), 
	POLE(0), 
	OTHER_WEAPON(0), 

	
	HELMET(1), 
	UPPER_PIECE(1), 
	LOWER_PIECE(1), 
	FULL_BODY(1), 
	GLOVES(1), 
	FEET(1), 
	SHIELD(1), 
	SIGIL(1), 
	UNDERWEAR(1), 
	CLOAK(1), 

	
	RING(2), 
	EARRING(2), 
	NECKLACE(2), 
	BELT(2), 
	BRACELET(2), 
	HAIR_ACCESSORY(2), 

	
	POTION(3), 
	SCROLL_ENCHANT_WEAPON(3), 
	SCROLL_ENCHANT_ARMOR(3), 
	SCROLL_OTHER(3), 
	SOULSHOT(3), 
	SPIRITSHOT(3), 
	NONE_41(-1),

	
	PET_EQUIPMENT(4), 
	PET_SUPPLIES(4), 

	
	CRYSTAL(5), 
	RECIPE(5), 
	CRAFTING_MAIN_INGRIDIENTS(5), 
	LIFE_STONE(5), 
	SOUL_CRYSTAL(5), 
	ATTRIBUTE_STONE(5), 
	WEAPON_ENCHANT_STONE(5), 
	ARMOR_ENCHANT_STONE(5), 
	SPELLBOOK(5), 
	GEMSTONE(5), 
	POUCH(5), 
	PIN(5), 
	MAGIC_RUNE_CLIP(5), 
	MAGIC_ORNAMENT(5), 
	DYES(5), 
	OTHER_ITEMS(5); 

	public static final ExItemType[] VALUES = values();

	private int _mask;

	ExItemType(int mask)
	{
		_mask = mask;
	}

	public int mask()
	{
		return _mask;
	}
}