package l2s.gameserver.stats.triggers;


public enum TriggerType
{
	ADD, 
	ATTACK,
	RECEIVE_DAMAGE, 
	CRIT, 
	OFFENSIVE_PHYSICAL_SKILL_USE, 
	OFFENSIVE_MAGICAL_SKILL_USE, 
	SUPPORT_MAGICAL_SKILL_USE, 
	UNDER_MISSED_ATTACK,
	DIE, 
	IDLE, 
    ON_REVIVE,	
	ON_START_EFFECT, 
	ON_EXIT_EFFECT, 
	ON_FINISH_EFFECT, 
	ON_START_CAST, 
	ON_TICK_CAST,
	ON_END_CAST, 
	ON_FINISH_CAST, 
	ON_ENTER_WORLD, 
	ON_KILL,	
	ON_CAST_SKILL; 
}