package l2s.gameserver.network.l2.components;


public enum ChatType
{
	ALL, 
	SHOUT, 
	TELL, 
	PARTY, 
	CLAN, 
	GM, 
	PETITION_PLAYER, 
	PETITION_GM, 
	TRADE, 
	ALLIANCE, 
	ANNOUNCEMENT, 
	SYSTEM_MESSAGE, 
    FRIENDTELL,
	MSNCHAT,
	PARTY_ROOM, 
	COMMANDCHANNEL_ALL, 
	COMMANDCHANNEL_COMMANDER, 
	HERO_VOICE, 
	CRITICAL_ANNOUNCE, 
	SCREEN_ANNOUNCE,
	BATTLEFIELD, 
	MPCC_ROOM, 
	NPC_ALL, 
	NPC_SHOUT, 
	BLUE_UNK,	
	WORLD; 

	public static final ChatType[] VALUES = values();
}