package l2s.gameserver.network.l2.components;

import java.util.NoSuchElementException;

import l2s.gameserver.model.Player;
import l2s.gameserver.network.l2.s2c.L2GameServerPacket;
import l2s.gameserver.network.l2.s2c.SystemMessagePacket;


public enum SystemMsg implements IBroadcastPacket
{
	
	THE_SERVER_WILL_BE_COMING_DOWN_IN_S1_SECONDS__PLEASE_FIND_A_SAFE_PLACE_TO_LOG_OUT(1),
	
	S1_IS_NOT_CURRENTLY_LOGGED_IN(3),
	
	YOU_CANNOT_ASK_YOURSELF_TO_APPLY_TO_A_CLAN(4),
	
	S1_IS_NOT_A_CLAN_LEADER(9),
	
	S1_IS_ALREADY_A_MEMBER_OF_ANOTHER_CLAN(10),
	
	UNABLE_TO_DISSOLVE_YOUR_CLAN_HAS_REQUESTED_TO_PARTICIPATE_IN_A_CASTLE_SIEGE(13),
	
	UNABLE_TO_DISSOLVE_YOUR_CLAN_OWNS_ONE_OR_MORE_CASTLES_OR_HIDEOUTS(14),
	
	YOU_ARE_NOT_IN_SIEGE(16),
	
	YOUR_TARGET_IS_OUT_OF_RANGE(22),
	
	NOT_ENOUGH_HP(23),
	
	NOT_ENOUGH_MP(24),
	
	REJUVENATING_HP(25),
	
	YOUR_CASTING_HAS_BEEN_INTERRUPTED(27),
	
	YOU_HAVE_OBTAINED_S2_S1(29),
	
	YOU_HAVE_OBTAINED_S1(30),
	
	YOU_CANNOT_MOVE_WHILE_SITTING(31),
	
	WELCOME_TO_THE_WORLD_OF_LINEAGE_II(34),
	
	YOU_HIT_FOR_S1_DAMAGE(35),
	
	YOU_CAREFULLY_NOCK_AN_ARROW(41),
	
	YOU_USE_S1(46),
	
	YOU_HAVE_EQUIPPED_YOUR_S1(49),
	
	YOUR_TARGET_CANNOT_BE_FOUND(50),
	
	YOU_CANNOT_USE_THIS_ON_YOURSELF(51),
	
	YOU_HAVE_EARNED_S1_ADENA(52),
	
	YOU_HAVE_EARNED_S2_S1S(53),
	
	YOU_HAVE_EARNED_S1(54),
	
	YOU_HAVE_FAILED_TO_PICK_UP_S1_ADENA(55),
	
	YOU_HAVE_FAILED_TO_PICK_UP_S1(56),
	
	NOTHING_HAPPENED(61),
	
	THIS_NAME_ALREADY_EXISTS(79),
	
	YOU_MAY_NOT_ATTACK_IN_A_PEACEFUL_ZONE(84),
	
	YOU_MAY_NOT_ATTACK_THIS_TARGET_IN_A_PEACEFUL_ZONE(85),
	
	YOUR_LEVEL_HAS_INCREASED(96),
	
	THIS_ITEM_CANNOT_BE_DISCARDED(98),
	
	THIS_ITEM_CANNOT_BE_TRADED_OR_SOLD(99),
	
	YOU_CANNOT_EXIT_THE_GAME_WHILE_IN_COMBAT(101),
	
	YOU_CANNOT_RESTART_WHILE_IN_COMBAT(102),
	
	YOU_CANNOT_CHANGE_WEAPONS_DURING_AN_ATTACK(104),
	
	C1_HAS_BEEN_INVITED_TO_THE_PARTY(105),
	
	INVALID_TARGET(109),
	
	S1S_EFFECT_CAN_BE_FELT(110),
	
	YOUR_SHIELD_DEFENSE_HAS_SUCCEEDED(111),
	
	YOU_HAVE_RUN_OUT_OF_ARROWS(112),
	
	S1_CANNOT_BE_USED_DUE_TO_UNSUITABLE_TERMS(113),
	
	YOU_HAVE_REQUESTED_A_TRADE_WITH_C1(118),
	
	C1_HAS_DENIED_YOUR_REQUEST_TO_TRADE(119),
	
	YOU_BEGIN_TRADING_WITH_C1(120),
	
	C1_HAS_CONFIRMED_THE_TRADE(121),
	
	YOU_MAY_NO_LONGER_ADJUST_ITEMS_IN_THE_TRADE_BECAUSE_THE_TRADE_HAS_BEEN_CONFIRMED(122),
	
	YOUR_TRADE_WAS_SUCCESSFUL(123),
	
	C1_HAS_CANCELLED_THE_TRADE(124),
	
	YOU_HAVE_BEEN_DISCONNECTED_FROM_THE_SERVER_(127),
	
	YOUR_INVENTORY_IS_FULL(129),
	
	YOUR_WAREHOUSE_IS_FULL(130),
	
	THERE_ARE_NO_MORE_ITEMS_IN_THE_SHORTCUT(137),
	
	C1_HAS_RESISTED_YOUR_S2(139),
	
	YOUR_SKILL_WAS_DEACTIVATED_DUE_TO_LACK_OF_MP(140),
	
	YOU_ARE_ALREADY_TRADING_WITH_SOMEONE(142),
	
	THAT_IS_AN_INCORRECT_TARGET(144),
	
	THAT_PLAYER_IS_NOT_ONLINE(145),
	
	YOU_CANNOT_USE_QUEST_ITEMS(148),
	
	YOU_CANNOT_DISCARD_SOMETHING_THAT_FAR_AWAY_FROM_YOU(151),
	
	YOU_HAVE_INVITED_THE_WRONG_TARGET(152),
	
	C1_IS_ON_ANOTHER_TASK(153),
	
	ONLY_THE_LEADER_CAN_GIVE_OUT_INVITATIONS(154),
	
	THE_PARTY_IS_FULL(155),
	
	YOUR_ATTACK_HAS_FAILED(158),
	
	C1_IS_A_MEMBER_OF_ANOTHER_PARTY_AND_CANNOT_BE_INVITED(160),
	
	THAT_PLAYER_IS_NOT_CURRENTLY_ONLINE(161),
	
	YOU_HAVE_MOVED_TOO_FAR_AWAY_FROM_THE_WAREHOUSE_TO_PERFORM_THAT_ACTION(162),
	
	YOU_CANNOT_DESTROY_IT_BECAUSE_THE_NUMBER_IS_INCORRECT(163),
	
	WAITING_FOR_ANOTHER_REPLY(164),
	
	YOU_CANNOT_ADD_YOURSELF_TO_YOUR_OWN_FRIEND_LIST(165),
	
	FRIEND_LIST_IS_NOT_READY_YET(166),
	
	C1_IS_ALREADY_ON_YOUR_FRIEND_LIST(167),
	
	C1_HAS_SENT_A_FRIEND_REQUEST(168),
	
	ACCEPT_FRIENDSHIP_01_1_TO_ACCEPT_0_TO_DENY(169),
	
	THE_USER_WHO_REQUESTED_TO_BECOME_FRIENDS_IS_NOT_FOUND_IN_THE_GAME(170),
	
	C1_IS_NOT_ON_YOUR_FRIEND_LIST(171),
	
	YOU_LACK_THE_FUNDS_NEEDED_TO_PAY_FOR_THIS_TRANSACTION(172),
	
	THAT_SKILL_HAS_BEEN_DEACTIVATED_AS_HP_WAS_FULLY_RECOVERED(175),
	
	THAT_PERSON_IS_IN_MESSAGE_REFUSAL_MODE(176),
	
	MESSAGE_REFUSAL_MODE(177),
	
	MESSAGE_ACCEPTANCE_MODE(178),
	
	CANNOT_SEE_TARGET(181),
	
	YOUR_CLAN_HAS_BEEN_CREATED(189),
	
	YOU_HAVE_FAILED_TO_CREATE_A_CLAN(190),
	
	CLAN_MEMBER_S1_HAS_BEEN_EXPELLED(191),
	
	CLAN_HAS_DISPERSED(193),
	
	ENTERED_THE_CLAN(195),
	
	S1_DECLINED_YOUR_CLAN_INVITATION(196),
	
	YOU_HAVE_RECENTLY_BEEN_DISMISSED_FROM_A_CLAN(199),
	
	YOU_HAVE_WITHDRAWN_FROM_THE_PARTY(200),
	YOU_REACHED_LEVEL_86_RELATIONSHIP_WITH_S1_CAME_TO_AN_END(3706),
	
	YOU_HAVE_OFFERED_TO_BECOME_S1_MENTOR(3707),
	
	YOU_CAN_BOND_WITH_A_NEW_MENTEE_IN_S1_DAYS_S2_HOUR_S3_MINUTE(3713),
	
	YOU_HAVE_BEEN_EXPELLED_FROM_THE_PARTY(202),
	
	INCORRECT_NAME(204),
	
	THE_SIZE_OF_THE_IMAGE_FILE_IS_INAPPROPRIATE__PLEASE_ADJUST_TO_16X12_PIXELS(209),
	
	YOU_ARE_NOT_A_CLAN_MEMBER_AND_CANNOT_PERFORM_THIS_ACTION(212),
	
	YOUR_TITLE_HAS_BEEN_CHANGED(214),
	
	A_CLAN_WAR_WITH_CLAN_S1_HAS_STARTED(215),
	
	WAR_WITH_THE_S1_CLAN_HAS_ENDED(216),
	
	YOU_HAVE_WON_THE_WAR_OVER_THE_S1_CLAN(217),
	
	YOU_HAVE_SURRENDERED_TO_THE_S1_CLAN(218),
	
	S1_HAS_JOINED_THE_CLAN(222),
	
	THE_MENTORING_RELATIONSHIP_WITH_S1_HAS_BEEN_CANCELED(3689),
	
	DO_TOU_WISH_TO_MAKE_S1_YOUR_MENTOR_CLASS_S2_LEVEL_S3(3690),
	
	FROM_NOW_ON_S1_WILL_BE_YOUR_MENTOR(3691),
	
	FROM_NOW_ON_S1_WILL_BE_YOUR_MENTEE(3692),
	
	A_MENTOR_CAN_HAVE_UP_TO_3_MENTEES_AT_THE_SAME_TIME(3693),
	
	YOU_MUST_AWAKEN_IN_ORDER_TO_BECOME_A_MENTOR(3694),
	
	YOU_MENTEE_S1_HAS_CONNECTED(3695),
	
	YOU_MENTOR_S1_HAS_CONNECTED(3696),
	
	YOU_MENTEE_S1_HAS_DISCONNECTED(3697),
	
	YOU_MENTOR_S1_HAS_DISCONNECTED(3698),
	
	S1_HAS_DECLINED_BECOMING_YOUR_MENTEE(3699),
	
	YOU_CANNOT_BECOME_YOUR_OWN_MENTEE(3701),
	
	S1_ALREADY_HAS_A_MENTOR(3702),
	
	S1_IS_ABOVE_LEVEL_86_AND_CANNOT_BECOME_A_MENTEE(3703),
	
	S1_DOES_NOT_HAVE_THE_ITEM_NEDEED_TO_BECOME_A_MENTEE(3704),
	
	THE_MENTEE_S1_HAS_REACHED_LEVEL_86(3705),
	
	INVITATION_CAN_OCCUR_ONLY_WHEN_THE_MENTEE_IS_IN_MAIN_CLASS_STATUS(3710),
	
	S1_HAS_WITHDRAWN_FROM_THE_CLAN(223),
	
	REQUEST_TO_END_WAR_HAS_BEEN_DENIED(228),
	
	YOU_DO_NOT_MEET_THE_CRITERIA_IN_ORDER_TO_CREATE_A_CLAN(229),
	
	YOU_MUST_WAIT_10_DAYS_BEFORE_CREATING_A_NEW_CLAN(230),
	
	AFTER_A_CLAN_MEMBER_IS_DISMISSED_FROM_A_CLAN_THE_CLAN_MUST_WAIT_AT_LEAST_A_DAY_BEFORE_ACCEPTING_A_NEW_MEMBER(231),
	
	AFTER_LEAVING_OR_HAVING_BEEN_DISMISSED_FROM_A_CLAN_YOU_MUST_WAIT_AT_LEAST_A_DAY_BEFORE_JOINING_ANOTHER_CLAN(232),
	
	THE_ACADEMYROYAL_GUARDORDER_OF_KNIGHTS_IS_FULL_AND_CANNOT_ACCEPT_NEW_MEMBERS_AT_THIS_TIME(233),
	
	THE_TARGET_MUST_BE_A_CLAN_MEMBER(234),
	
	ONLY_THE_CLAN_LEADER_IS_ENABLED(236),
	
	NOT_JOINED_IN_ANY_CLAN(238),
	
	A_CLAN_LEADER_CANNOT_WITHDRAW_FROM_THEIR_OWN_CLAN(239),
	
	SELECT_TARGET(242),
	
	YOU_HAVE_ALREADY_BEEN_AT_WAR_WITH_THE_S1_CLAN_5_DAYS_MUST_PASS_BEFORE_YOU_CAN_CHALLENGE_THIS_CLAN_AGAIN(247),
	
	CLAN_NAME_IS_INVALID(261),
	
	CLAN_NAMES_LENGTH_IS_INCORRECT(262),
	
	YOU_HAVE_ALREADY_REQUESTED_THE_DISSOLUTION_OF_YOUR_CLAN(263),
	
	YOU_CANNOT_DISSOLVE_A_CLAN_WHILE_ENGAGED_IN_A_WAR(264),
	
	THERE_ARE_NO_REQUESTS_TO_DISPERSE(267),
	
	A_PLAYER_CAN_ONLY_BE_GRANTED_A_TITLE_IF_THE_CLAN_IS_LEVEL_3_OR_ABOVE(271),
	
	A_CLAN_CREST_CAN_ONLY_BE_REGISTERED_WHEN_THE_CLANS_SKILL_LEVEL_IS_3_OR_ABOVE(272),
	
	YOUR_CLANS_LEVEL_HAS_INCREASED(274),
	
	THE_CLAN_HAS_FAILED_TO_INCREASE_ITS_LEVEL(275),
	
	YOU_DO_NOT_HAVE_THE_NECESSARY_MATERIALS_OR_PREREQUISITES_TO_LEARN_THIS_SKILL(276),
	
	YOU_HAVE_EARNED_S1_SKILL(277),
	
	YOU_DO_NOT_HAVE_ENOUGH_ADENA(279),
	
	YOU_DO_NOT_HAVE_ENOUGH_SP_TO_LEARN_THIS_SKILL(278),
	
	YOU_HAVE_NOT_DEPOSITED_ANY_ITEMS_IN_YOUR_WAREHOUSE(282),
	
	YOU_HAVE_ENTERED_A_COMBAT_ZONE(283),
	
	YOU_HAVE_LEFT_A_COMBAT_ZONE(284),
	
	CLAN_S1_HAS_SUCCESSFULLY_ENGRAVED_THE_HOLY_ARTIFACT(285),
	
	YOUR_BASE_IS_BEING_ATTACKED(286),
	
	THE_OPPOSING_CLAN_HAS_STARTED_TO_ENGRAVE_THE_HOLY_ARTIFACT(287),
	
	THE_CASTLE_GATE_HAS_BEEN_DESTROYED(288),
	
	AN_OUTPOST_OR_HEADQUARTERS_CANNOT_BE_BUILT_BECAUSE_ONE_ALREADY_EXISTS(289),
	
	YOU_CANNOT_SET_UP_A_BASE_HERE(290),
	
	CLAN_S1_IS_VICTORIOUS_OVER_S2S_CASTLE_SIEGE(291),
	
	S1_HAS_ANNOUNCED_THE_NEXT_CASTLE_SIEGE_TIME(292),
	
	THE_REGISTRATION_TERM_FOR_S1_HAS_ENDED(293),
	
	YOU_CANNOT_SUMMON_THE_ENCAMPMENT_BECAUSE_YOU_ARE_NOT_A_MEMBER_OF_THE_SIEGE_CLAN_INVOLVED_IN_THE_CASTLE__FORTRESS__HIDEOUT_SIEGE(294),
	
	S1S_SIEGE_WAS_CANCELED_BECAUSE_THERE_WERE_NO_CLANS_THAT_PARTICIPATED(295),
	
	YOU_HAVE_DROPPED_S1(298),
	
	C1_HAS_OBTAINED_S3_S2(299),
	
	C1_HAS_OBTAINED_S2(300),
	
	S2_S1_HAS_DISAPPEARED(301),
	
	S1_HAS_DISAPPEARED(302),
	
	CLAN_MEMBER_S1_HAS_LOGGED_INTO_GAME(304),
	
	THE_PLAYER_DECLINED_TO_JOIN_YOUR_PARTY(305),
	
    YOU_HAVE_FAILED_TO_WITHDRAW_FROM_THE_PARTY(316),
    
    YOU_HAVE_FAILED_TO_EXPEL_THE_PARTY_MEMBER(317),
	
	THIS_DOOR_CANNOT_BE_UNLOCKED(319),
	
	YOU_HAVE_FAILED_TO_UNLOCK_THE_DOOR(320),
	
	IT_IS_NOT_LOCKED(321),
	
	THE_SOULSHOT_YOU_ARE_ATTEMPTING_TO_USE_DOES_NOT_MATCH_THE_GRADE_OF_YOUR_EQUIPPED_WEAPON(337),
	
	YOU_DO_NOT_HAVE_ENOUGH_SOULSHOTS_FOR_THAT(338),
	
	CANNOT_USE_SOULSHOTS(339),
	
	YOU_DO_NOT_HAVE_ENOUGH_MATERIALS_TO_PERFORM_THAT_ACTION(341),
	
	YOUR_SOULSHOTS_ARE_ENABLED(342),
	
	SWEEPER_FAILED_TARGET_NOT_SPOILED(343),
	
	INCORRECT_ITEM_COUNT(351),
	
	INAPPROPRIATE_ENCHANT_CONDITIONS(355),
	
	REJECT_RESURRECTION(356),
	
	IT_HAS_ALREADY_BEEN_SPOILED(357),
	
	S1_HOURS_UNTIL_CASTLE_SIEGE_CONCLUSION(358),
	
	S1_MINUTES_UNTIL_CASTLE_SIEGE_CONCLUSION(359),
	
	THIS_CASTLE_SIEGE_WILL_END_IN_S1_SECONDS(360),
	
	OVERHIT(361),
	
	YOU_HAVE_OBTAINED_A_S1_S2(369),
	
	C1_HAS_OBTAINED_S2S3(376),
	
	S1_S2_DISAPPEARED(377),
	
	C1_PURCHASED_S2(378),
	
	C1_PURCHASED_S2S3(379),
	
	C1_PURCHASED_S3_S2S(380),
	
	FAILED_TO_CANCEL_PETITION_PLEASE_TRY_AGAIN_LATER(393),
	
	SYSTEM_ERROR(399),
	
	YOU_DO_NOT_POSSESS_THE_CORRECT_TICKET_TO_BOARD_THE_BOAT(402),
	
	YOUR_CREATE_ITEM_LEVEL_IS_TOO_LOW_TO_REGISTER_THIS_RECIPE(404),
	
	YOUR_PETITION_IS_BEING_PROCESSED(407),
	
	TIME_EXPIRED(420),
	
	ANOTHER_PERSON_HAS_LOGGED_IN_WITH_THE_SAME_ACCOUNT(421),
	
	YOU_HAVE_EXCEEDED_THE_WEIGHT_LIMIT(422),
	
	DOES_NOT_FIT_STRENGTHENING_CONDITIONS_OF_THE_SCROLL(424),
	
	THIS_FEATURE_IS_ONLY_AVAILABLE_TO_ALLIANCE_LEADERS(464),
	
	YOU_ARE_NOT_CURRENTLY_ALLIED_WITH_ANY_CLANS(465),
	
	A_CLAN_THAT_HAS_WITHDRAWN_OR_BEEN_EXPELLED_CANNOT_ENTER_INTO_AN_ALLIANCE_WITHIN_ONE_DAY_OF_WITHDRAWAL_OR_EXPULSION(468),
	
	YOU_MAY_NOT_ALLY_WITH_A_CLAN_YOU_ARE_CURRENTLY_AT_WAR_WITH(469),
	
	ONLY_THE_CLAN_LEADER_MAY_APPLY_FOR_WITHDRAWAL_FROM_THE_ALLIANCE(470),
	
	ALLIANCE_LEADERS_CANNOT_WITHDRAW(471),
	
	S1_HAS_JOINED_AS_A_FRIEND(479),
	
	FRIENDS_LIST(487),
	
	LINE_490(490),
	
	ALLIANCE_INFORMATION(491),
	
	CLAN_INFORMATION(496),
	
	LINE_500(500),
	
	YOU_ALREADY_BELONG_TO_ANOTHER_ALLIANCE(502),
	
	ONLY_CLAN_LEADERS_MAY_CREATE_ALLIANCES(504),
	
	YOU_CANNOT_CREATE_A_NEW_ALLIANCE_WITHIN_1_DAY_OF_DISSOLUTION(505),
	
	INCORRECT_ALLIANCE_NAME__PLEASE_TRY_AGAIN(506),
	
	INCORRECT_LENGTH_FOR_AN_ALLIANCE_NAME(507),
	
	THAT_ALLIANCE_NAME_ALREADY_EXISTS(508),
	
	YOU_HAVE_ACCEPTED_THE_ALLIANCE(517),
	
	YOU_HAVE_FAILED_TO_INVITE_A_CLAN_INTO_THE_ALLIANCE(518),
	
	YOU_HAVE_WITHDRAWN_FROM_THE_ALLIANCE(519),
	
	YOU_HAVE_FAILED_TO_WITHDRAW_FROM_THE_ALLIANCE(520),
	
	THE_ALLIANCE_HAS_BEEN_DISSOLVED(523),
	
	YOU_HAVE_FAILED_TO_DISSOLVE_THE_ALLIANCE(524),
	
	THAT_PERSON_HAS_BEEN_SUCCESSFULLY_ADDED_TO_YOUR_FRIEND_LIST(525),
	
	YOU_HAVE_FAILED_TO_ADD_A_FRIEND_TO_YOUR_FRIENDS_LIST(526),
	
	S1_LEADER_S2_HAS_REQUESTED_AN_ALLIANCE(527),
	
	YOUR_SPIRITSHOT_DOES_NOT_MATCH_THE_WEAPONS_GRADE(530),
	
	YOU_DO_NOT_HAVE_ENOUGH_SPIRITSHOT_FOR_THAT(531),
	
	YOU_MAY_NOT_USE_SPIRITSHOTS(532),
	
	YOUR_SPIRITSHOT_HAS_BEEN_ENABLED(533),
	
	YOUR_SP_HAS_DECREASED_BY_S1(538),
	
	YOU_ALREADY_HAVE_A_PET(543),
	
	YOUR_PET_CANNOT_CARRY_THIS_ITEM(544),
	
	YOUR_PET_CANNOT_CARRY_ANY_MORE_ITEMS(545),
	
	YOUR_PET_CANNOT_CARRY_ANY_MORE_ITEMS_(546),
	
	SUMMONING_YOUR_PET(547),
	
	YOUR_PETS_NAME_CAN_BE_UP_TO_8_CHARACTERS_IN_LENGTH(548),
	
	TO_CREATE_AN_ALLIANCE_YOUR_CLAN_MUST_BE_LEVEL_5_OR_HIGHER(549),
	
	AS_YOU_ARE_CURRENTLY_SCHEDULE_FOR_CLAN_DISSOLUTION_NO_ALLIANCE_CAN_BE_CREATED(550),
	
	AS_YOU_ARE_CURRENTLY_SCHEDULE_FOR_CLAN_DISSOLUTION_YOUR_CLAN_LEVEL_CANNOT_BE_INCREASED(551),
	
	AS_YOU_ARE_CURRENTLY_SCHEDULE_FOR_CLAN_DISSOLUTION_YOU_CANNOT_REGISTER_OR_DELETE_A_CLAN_CREST(552),
	
	YOU_CANNOT_DISPERSE_THE_CLANS_IN_YOUR_ALLIANCE(554),
	
	AS_YOUR_PET_IS_CURRENTLY_OUT_ITS_SUMMONING_ITEM_CANNOT_BE_DESTROYED(557),
	
	YOU_MAY_NOT_CRYSTALLIZE_THIS_ITEM(562),
	
	CUBIC_SUMMONING_FAILED(568),
	
	PETS_AND_SERVITORS_ARE_NOT_AVAILABLE_AT_THIS_TIME(574),
	
	YOU_CANNOT_SUMMON_DURING_A_TRADE_OR_WHILE_USING_A_PRIVATE_STORE(577),
	
	YOU_CANNOT_SUMMON_DURING_COMBAT(578),
	
	A_PET_CANNOT_BE_UNSUMMONED_DURING_BATTLE(579),
	
	YOU_MAY_NOT_USE_MULTIPLE_PETS_OR_SERVITORS_AT_THE_SAME_TIME(580),
	
	DEAD_PETS_CANNOT_BE_RETURNED_TO_THEIR_SUMMONING_ITEM(589),
	
	YOUR_PET_IS_DEAD_AND_ANY_ATTEMPT_YOU_MAKE_TO_GIVE_IT_SOMETHING_GOES_UNRECOGNIZED(590),
	
	YOU_MAY_NOT_RESTORE_A_HUNGRY_PET(594),
	
	YOUR_PET_IS_VERY_HUNGRY(595),
	
	YOUR_PET_ATE_A_LITTLE_BUT_IS_STILL_HUNGRY(596),
	
	YOU_MAY_NOT_EQUIP_A_PET_ITEM(600),
	
	YOU_MAY_NOT_CALL_FORTH_A_PET_OR_SUMMONED_CREATURE_FROM_THIS_LOCATION(604),
	
	YOU_CAN_ONLY_ENTER_UP_128_NAMES_IN_YOUR_FRIENDS_LIST(605),
	
	THE_FRIENDS_LIST_OF_THE_PERSON_YOU_ARE_TRYING_TO_ADD_IS_FULL_SO_REGISTRATION_IS_NOT_POSSIBLE(606),
	
	YOU_DO_NOT_HAVE_ANY_FURTHER_SKILLS_TO_LEARN__COME_BACK_WHEN_YOU_HAVE_REACHED_LEVEL_S1(607),
	
	C1_HAS_OBTAINED_S3_S2_BY_USING_SWEEPER(608),
	
	C1_HAS_OBTAINED_S2_BY_USING_SWEEPER(609),
	
	THE_SPOIL_CONDITION_HAS_BEEN_ACTIVATED(612),
	
	IGNORE_LIST(613),
	
	YOU_HAVE_FAILED_TO_REGISTER_THE_USER_TO_YOUR_IGNORE_LIST(615),
	
	YOU_HAVE_FAILED_TO_DELETE_THE_CHARACTER_(616),
	
	S1_HAS_BEEN_ADDED_TO_YOUR_IGNORE_LIST(617),
	
	S1_HAS_BEEN_REMOVED_FROM_YOUR_IGNORE_LIST(618),
	
	C1_HAS_PLACED_YOU_ON_HISHER_IGNORE_LIST(619),
	
	THE_S1_CLAN_DID_NOT_RESPOND_WAR_PROCLAMATION_HAS_BEEN_REFUSED(626),
	
	YOU_HAVE_ALREADY_BEEN_AT_WAR_WITH_THE_S1_CLAN_5_DAYS_MUST_PASS_BEFORE_YOU_CAN_DECLARE_WAR_AGAIN(628),
	
	YOU_HAVE_ALREADY_REQUESTED_A_CASTLE_SIEGE(638),
	
	YOU_ARE_ALREADY_REGISTERED_TO_THE_ATTACKER_SIDE_AND_MUST_CANCEL_YOUR_REGISTRATION_BEFORE_SUBMITTING_YOUR_REQUEST(642),
	
	YOU_HAVE_ALREADY_REGISTERED_TO_THE_DEFENDER_SIDE_AND_MUST_CANCEL_YOUR_REGISTRATION_BEFORE_SUBMITTING_YOUR_REQUEST(643),
	
	YOU_ARE_NOT_YET_REGISTERED_FOR_THE_CASTLE_SIEGE(644),
	
	ONLY_CLANS_OF_LEVEL_5_OR_HIGHER_MAY_REGISTER_FOR_A_CASTLE_SIEGE(645),
	
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_MODIFY_THE_CASTLE_DEFENDER_LIST(646),
	
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_MODIFY_THE_SIEGE_TIME(647),
	
	NO_MORE_REGISTRATIONS_MAY_BE_ACCEPTED_FOR_THE_ATTACKER_SIDE(648),
	
	NO_MORE_REGISTRATIONS_MAY_BE_ACCEPTED_FOR_THE_DEFENDER_SIDE(649),
	
	YOU_MAY_NOT_SUMMON_FROM_YOUR_CURRENT_LOCATION(650),
	
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_POSITION_MERCENARIES(653),
	
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_CANCEL_MERCENARY_POSITIONING(654),
	
	MERCENARIES_CANNOT_BE_POSITIONED_HERE(655),
	
	THIS_MERCENARY_CANNOT_BE_POSITIONED_ANYMORE(656),
	
	POSITIONING_CANNOT_BE_DONE_HERE_BECAUSE_THE_DISTANCE_BETWEEN_MERCENARIES_IS_TOO_SHORT(657),
	
	THIS_IS_NOT_A_MERCENARY_OF_A_CASTLE_THAT_YOU_OWN_AND_SO_YOU_CANNOT_CANCEL_ITS_POSITIONING(658),
	
	THIS_IS_NOT_THE_TIME_FOR_SIEGE_REGISTRATION_AND_SO_REGISTRATIONS_CANNOT_BE_ACCEPTED_OR_REJECTED(659),
	
	THIS_IS_NOT_THE_TIME_FOR_SIEGE_REGISTRATION_AND_SO_REGISTRATION_AND_CANCELLATION_CANNOT_BE_DONE(660),
	
	S1_ADENA_DISAPPEARED(672),
	
	ONLY_A_CLAN_LEADER_WHOSE_CLAN_IS_OF_LEVEL_2_OR_HIGHER_IS_ALLOWED_TO_PARTICIPATE_IN_A_CLAN_HALL_AUCTION(673),
	
	IT_HAS_NOT_YET_BEEN_SEVEN_DAYS_SINCE_CANCELING_AN_AUCTION(674),
	
	THERE_ARE_NO_CLAN_HALLS_UP_FOR_AUCTION(675),
	
	SINCE_YOU_HAVE_ALREADY_SUBMITTED_A_BID_YOU_ARE_NOT_ALLOWED_TO_PARTICIPATE_IN_ANOTHER_AUCTION_AT_THIS_TIME(676),
	
	YOUR_BID_PRICE_MUST_BE_HIGHER_THAN_THE_MINIMUM_PRICE_CURRENTLY_BEING_BID(677),
	
	YOU_HAVE_CANCELED_YOUR_BID(679),
	
	THERE_ARE_NO_PRIORITY_RIGHTS_ON_A_SWEEPER(683),
	
	YOU_CANNOT_MOVE_WHILE_FROZEN(687),
	
	CASTLE_OWNING_CLANS_ARE_AUTOMATICALLY_REGISTERED_ON_THE_DEFENDING_SIDE(688),
	
	A_CLAN_THAT_OWNS_A_CASTLE_CANNOT_PARTICIPATE_IN_ANOTHER_SIEGE(689),
	
	YOU_CANNOT_REGISTER_AS_AN_ATTACKER_BECAUSE_YOU_ARE_IN_AN_ALLIANCE_WITH_THE_CASTLE_OWNING_CLAN(690),
	
	S1_CLAN_IS_ALREADY_A_MEMBER_OF_S2_ALLIANCE(691),
	
	THE_OTHER_PARTY_IS_FROZEN(692),
	
	NO_PACKAGES_HAVE_ARRIVED(694),
	
	YOU_DO_NOT_HAVE_ENOUGH_REQUIRED_ITEMS(701),
	
	THERE_ARE_NO_GMS_CURRENTLY_VISIBLE_IN_THE_PUBLIC_LIST_AS_THEY_MAY_BE_PERFORMING_OTHER_FUNCTIONS_AT_THE_MOMENT(702),
	
	GM_LIST(703),
	
	GM__C1(704),
	
	YOU_CANNOT_TELEPORT_TO_A_VILLAGE_THAT_IS_IN_A_SIEGE(707),
	
	YOU_DO_NOT_HAVE_THE_RIGHT_TO_USE_THE_CLAN_WAREHOUSE(709),
	
	ONLY_CLANS_OF_CLAN_LEVEL_1_OR_HIGHER_CAN_USE_A_CLAN_WAREHOUSE(710),
	
	IF_A_BASE_CAMP_DOES_NOT_EXIST_RESURRECTION_IS_NOT_POSSIBLE(716),
	
	THE_GUARDIAN_TOWER_HAS_BEEN_DESTROYED_AND_RESURRECTION_IS_NOT_POSSIBLE(717),
	
	THE_PURCHASE_PRICE_IS_HIGHER_THAN_THE_AMOUNT_OF_MONEY_THAT_YOU_HAVE_AND_SO_YOU_CANNOT_OPEN_A_PERSONAL_STORE(720),
	
	YOU_CANNOT_APPLY_FOR_DISSOLUTION_AGAIN_WITHIN_SEVEN_DAYS_AFTER_A_PREVIOUS_APPLICATION_FOR_DISSOLUTION(728),
	
	THAT_ITEM_CANNOT_BE_DISCARDED(729),
	
	THE_PETITION_WAS_CANCELED_YOU_MAY_SUBMIT_S1_MORE_PETITIONS_TODAY(736),
	
	YOU_HAVE_NOT_SUBMITTED_A_PETITION(738),
	
	YOU_ARE_CURRENTLY_NOT_IN_A_PETITION_CHAT(745),
	
	THE_DISTANCE_IS_TOO_FAR_AND_SO_THE_CASTING_HAS_BEEN_STOPPED(748),
	
	THE_EFFECT_OF_S1_HAS_BEEN_REMOVED(749),
	
	THERE_ARE_NO_OTHER_SKILLS_TO_LEARN(750),
	
	YOU_CANNOT_POSITION_MERCENARIES_HERE(753),
	
	C1_CANNOT_JOIN_THE_CLAN_BECAUSE_ONE_DAY_HAS_NOT_YET_PASSED_SINCE_THEY_LEFT_ANOTHER_CLAN(760),
	
	S1_CLAN_CANNOT_JOIN_THE_ALLIANCE_BECAUSE_ONE_DAY_HAS_NOT_YET_PASSED_SINCE_THEY_LEFT_ANOTHER_ALLIANCE(761),
	
	THE_CLAN_HALL_WHICH_WAS_PUT_UP_FOR_AUCTION_HAS_BEEN_AWARDED_TO_S1_CLAN(776),
	
	THE_CLAN_HALL_WHICH_HAD_BEEN_PUT_UP_FOR_AUCTION_WAS_NOT_SOLD_AND_THEREFORE_HAS_BEEN_RELISTED(777),
	
	OBSERVATION_IS_ONLY_POSSIBLE_DURING_A_SIEGE(780),
	
	OBSERVERS_CANNOT_PARTICIPATE(781),
	
	LOTTERY_TICKET_SALES_HAVE_BEEN_TEMPORARILY_SUSPENDED(783),
	
	TICKETS_FOR_THE_CURRENT_LOTTERY_ARE_NO_LONGER_AVAILABLE(784),
	
	THE_TRYOUTS_ARE_FINISHED(787),
	
	THE_FINALS_ARE_FINISHED(788),
	
	THE_TRYOUTS_HAVE_BEGUN(789),
	
	THE_FINALS_HAVE_BEGUN(790),
	
	THE_FINAL_MATCH_IS_ABOUT_TO_BEGIN(791),
	
	YOU_ARE_NOT_AUTHORIZED_TO_DO_THAT(794),
	
	YOU_MAY_CREATE_UP_TO_48_MACROS(797),
	
	YOU_ARE_TOO_LATE_THE_REGISTRATION_PERIOD_IS_OVER(800),
	
	THE_TRYOUTS_ARE_ABOUT_TO_BEGIN(815),
	
	THEYRE_OFF(824),
	
	YOU_MAY_NOT_IMPOSE_A_BLOCK_ON_A_GM(827),
	
	YOU_CANNOT_RECOMMEND_YOURSELF(829),
	
	YOU_HAVE_RECOMMENDED_C1_YOU_HAVE_S2_RECOMMENDATIONS_LEFT(830),
	
	YOU_HAVE_BEEN_RECOMMENDED_BY_C1(831),
	
	YOU_ARE_NOT_AUTHORIZED_TO_MAKE_FURTHER_RECOMMENDATIONS_AT_THIS_TIME(833),
	
	YOU_MAY_NOT_THROW_THE_DICE_AT_THIS_TIME(835),
	
	MACRO_DESCRIPTIONS_MAY_CONTAIN_UP_TO_32_CHARACTERS(837),
	
	ENTER_THE_NAME_OF_THE_MACRO(838),
	
	THAT_RECIPE_IS_ALREADY_REGISTERED(840),
	
	NO_FURTHER_RECIPES_MAY_BE_REGISTERED(841),
	
	YOU_ARE_NOT_AUTHORIZED_TO_REGISTER_A_RECIPE(842),
	
	THE_SIEGE_OF_S1_IS_FINISHED(843),
	
	THE_SIEGE_TO_CONQUER_S1_HAS_BEGUN(844),
	
	THE_DEADLINE_TO_REGISTER_FOR_THE_SIEGE_OF_S1_HAS_PASSED(845),
	
	THE_SIEGE_OF_S1_HAS_BEEN_CANCELED_DUE_TO_LACK_OF_INTEREST(846),
	
	A_CLAN_THAT_OWNS_A_CLAN_HALL_MAY_NOT_PARTICIPATE_IN_A_CLAN_HALL_SIEGE(847),
	
	THE_RECIPE_IS_INCORRECT(852),
	
	S1_CLAN_HAS_DEFEATED_S2(855),
	
	THE_SIEGE_OF_S1_HAS_ENDED_IN_A_DRAW(856),
	
	PLEASE_REGISTER_A_RECIPE(859),
	
	THE_SEED_HAS_BEEN_SOWN(871),
	
	THIS_SEED_MAY_NOT_BE_SOWN_HERE(872),
	
	THE_SYMBOL_HAS_BEEN_ADDED(877),
	
	THE_PRELIMINARY_MATCH_OF_S1_HAS_ENDED_IN_A_DRAW(858),
	
	THE_SYMBOL_HAS_BEEN_DELETED(878),
	
	THE_MANOR_SYSTEM_IS_CURRENTLY_UNDER_MAINTENANCE(879),
	
	THE_TRANSACTION_IS_COMPLETE(880),
	
	THE_MANOR_INFORMATION_HAS_BEEN_UPDATED(884),
	
	THE_SEED_WAS_SUCCESSFULLY_SOWN(889),
	
	THE_SEED_WAS_NOT_SOWN(890),
	
	YOU_ARE_NOT_AUTHORIZED_TO_HARVEST(891),
	
	THE_HARVEST_HAS_FAILED(892),
	
	THE_HARVEST_FAILED_BECAUSE_THE_SEED_WAS_NOT_SOWN(893),
	
	THE_SYMBOL_CANNOT_BE_DRAWN(899),
	
	NO_SLOT_EXISTS_TO_DRAW_THE_SYMBOL(900),
	
	LOTTERY_TICKETS_ARE_NOT_CURRENTLY_BEING_SOLD(930),
	
	YOU_CANNOT_CHAT_WHILE_IN_OBSERVATION_MODE(932),
	
	YOU_DO_NOT_HAVE_ENOUGH_FUNDS_IN_THE_CLAN_WAREHOUSE_FOR_THE_MANOR_TO_OPERATE(935),
	
	THE_COMMUNITY_SERVER_IS_CURRENTLY_OFFLINE(938),
	
	YOU_FAILED_TO_MANUFACTURE_S1(960),
	
	YOU_ARE_NOW_BLOCKING_EVERYTHING(961),
	
	YOU_ARE_NO_LONGER_BLOCKING_EVERYTHING(962),
	
	PLEASE_DETERMINE_THE_MANUFACTURING_PRICE(963),
	
	CHATTING_IS_PROHIBITED_FOR_ONE_MINUTE(964),
	
	THE_CHATTING_PROHIBITION_HAS_BEEN_REMOVED(965),
	
	CHATTING_IS_CURRENTLY_PROHIBITED_IF_YOU_TRY_TO_CHAT_BEFORE_THE_PROHIBITION_IS_REMOVED_THE_PROHIBITION_TIME_WILL_INCREASE_EVEN_FURTHER(966),
	
	DO_YOU_ACCEPT_C1S_PARTY_INVITATION_ITEM_DISTRIBUTION_RANDOM_INCLUDING_SPOIL(967),
	
	DO_YOU_ACCEPT_C1S_PARTY_INVITATION_ITEM_DISTRIBUTION_BY_TURN(968),
	
	DO_YOU_ACCEPT_C1S_PARTY_INVITATION_ITEM_DISTRIBUTION_BY_TURN_INCLUDING_SPOIL(969),
	
	S2S_MP_HAS_BEEN_DRAINED_BY_C1(970),
	
	THE_PETITION_CAN_CONTAIN_UP_TO_800_CHARACTERS(971),
	
	THIS_PET_CANNOT_USE_THIS_ITEM(972),
	
	PLEASE_INPUT_NO_MORE_THAN_THE_NUMBER_YOU_HAVE(973),
	
	THE_SOUL_CRYSTAL_SUCCEEDED_IN_ABSORBING_A_SOUL(974),
	
	THE_SOUL_CRYSTAL_WAS_NOT_ABLE_TO_ABSORB_THE_SOUL(975),
	
	THE_SOUL_CRYSTAL_BROKE_BECAUSE_IT_WAS_NOT_ABLE_TO_ENDURE_THE_SOUL_ENERGY(976),
	
	THE_SOUL_CRYSTAL_CAUSED_RESONATION_AND_FAILED_AT_ABSORBING_A_SOUL(977),
	
	THE_SOUL_CRYSTAL_IS_REFUSING_TO_ABSORB_THE_SOUL(978),
	
	THE_FERRY_HAS_ARRIVED_AT_TALKING_ISLAND_HARBOR(979),
	
	THE_FERRY_WILL_LEAVE_FOR_GLUDIN_HARBOR_AFTER_ANCHORING_FOR_TEN_MINUTES(980),
	
	THE_FERRY_WILL_LEAVE_FOR_GLUDIN_HARBOR_IN_FIVE_MINUTES(981),
	
	THE_FERRY_WILL_LEAVE_FOR_GLUDIN_HARBOR_IN_ONE_MINUTE(982),
	
	THOSE_WISHING_TO_RIDE_THE_FERRY_SHOULD_MAKE_HASTE_TO_GET_ON(983),
	
	THE_FERRY_WILL_BE_LEAVING_SOON_FOR_GLUDIN_HARBOR(984),
	
	THE_FERRY_IS_LEAVING_FOR_GLUDIN_HARBOR(985),
	
	THE_FERRY_HAS_ARRIVED_AT_GLUDIN_HARBOR(986),
	
	THE_FERRY_WILL_LEAVE_FOR_TALKING_ISLAND_HARBOR_AFTER_ANCHORING_FOR_TEN_MINUTES(987),
	
	THE_FERRY_WILL_LEAVE_FOR_TALKING_ISLAND_HARBOR_IN_FIVE_MINUTES(988),
	
	THE_FERRY_WILL_LEAVE_FOR_TALKING_ISLAND_HARBOR_IN_ONE_MINUTE(989),
	
	THE_FERRY_WILL_BE_LEAVING_SOON_FOR_TALKING_ISLAND_HARBOR(990),
	
	THE_FERRY_IS_LEAVING_FOR_TALKING_ISLAND_HARBOR(991),
	
	THE_FERRY_HAS_ARRIVED_AT_GIRAN_HARBOR(992),
	
	THE_FERRY_WILL_LEAVE_FOR_GIRAN_HARBOR_AFTER_ANCHORING_FOR_TEN_MINUTES(993),
	
	THE_FERRY_WILL_LEAVE_FOR_GIRAN_HARBOR_IN_FIVE_MINUTES(994),
	
	THE_FERRY_WILL_LEAVE_FOR_GIRAN_HARBOR_IN_ONE_MINUTE(995),
	
	THE_FERRY_WILL_BE_LEAVING_SOON_FOR_GIRAN_HARBOR(996),
	
	THE_FERRY_IS_LEAVING_FOR_GIRAN_HARBOR(997),
	
	THE_INNADRIL_PLEASURE_BOAT_HAS_ARRIVED_IT_WILL_ANCHOR_FOR_TEN_MINUTES(998),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_LEAVE_IN_FIVE_MINUTES(999),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_LEAVE_IN_ONE_MINUTE(1000),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_BE_LEAVING_SOON(1001),
	
	THE_INNADRIL_PLEASURE_BOAT_IS_LEAVING(1002),
	
	CANNOT_PROCESS_A_MONSTER_RACE_TICKET(1003),
	
	YOU_HAVE_REGISTERED_FOR_A_CLAN_HALL_AUCTION(1004),
	
	THERE_IS_NOT_ENOUGH_ADENA_IN_THE_CLAN_HALL_WAREHOUSE(1005),
	
	YOUR_BID_HAS_BEEN_SUCCESSFULLY_PLACED(1006),
	
	THE_PRELIMINARY_MATCH_REGISTRATION_FOR_S1_HAS_FINISHED(1007),
	
	A_HUNGRY_STRIDER_CANNOT_BE_MOUNTED_OR_DISMOUNTED(1008),
	
	A_STRIDER_CANNOT_BE_RIDDEN_WHEN_DEAD(1009),
	
	A_DEAD_STRIDER_CANNOT_BE_RIDDEN(1010),
	
	A_STRIDER_IN_BATTLE_CANNOT_BE_RIDDEN(1011),
	
	A_STRIDER_CANNOT_BE_RIDDEN_WHILE_IN_BATTLE(1012),
	
	A_STRIDER_CAN_BE_RIDDEN_ONLY_WHEN_STANDING(1013),
	
	YOUR_PET_GAINED_S1_XP(1014),
	
	YOUR_PET_HIT_FOR_S1_DAMAGE(1015),
	
	YOUR_PET_RECEIVED_S2_DAMAGE_BY_C1(1016),
	
	PETS_CRITICAL_HIT(1017),
	
	SUMMONED_MONSTERS_CRITICAL_HIT(1028),
	
	PARTY_INFORMATION(1030),
	
	LOOTING_METHOD_FINDERS_KEEPERS(1031),
	
	LOOTING_METHOD_RANDOM(1032),
	
	LOOTING_METHOD_RANDOM_INCLUDING_SPOIL(1033),
	
	LOOTING_METHOD_BY_TURN(1034),
	
	LOOTING_METHOD_BY_TURN_INCLUDING_SPOIL(1035),
	
	YOU_HAVE_EXCEEDED_THE_QUANTITY_THAT_CAN_BE_INPUTTED(1036),
	
	ITEMS_LEFT_AT_THE_CLAN_HALL_WAREHOUSE_CAN_ONLY_BE_RETRIEVED_BY_THE_CLAN_LEADER(1039),
	
	MONSTER_RACE_PAYOUT_INFORMATION_IS_NOT_AVAILABLE_WHILE_TICKETS_ARE_BEING_SOLD(1044),
	
	MONSTER_RACE_TICKETS_ARE_NO_LONGER_AVAILABLE(1046),
	
	PAYMENT_FOR_YOUR_CLAN_HALL_HAS_NOT_BEEN_MADE_PLEASE_ME_PAYMENT_TO_YOUR_CLAN_WAREHOUSE_BY_S1_TOMORROW(1051),
	
	THE_CLAN_HALL_FEE_IS_ONE_WEEK_OVERDUE_THEREFORE_THE_CLAN_HALL_OWNERSHIP_HAS_BEEN_REVOKED(1052),
	
	IT_IS_NOT_POSSIBLE_TO_RESURRECT_IN_BATTLEFIELDS_WHERE_A_SIEGE_WAR_IS_TAKING_PLACE(1053),
	
	WHILE_OPERATING_A_PRIVATE_STORE_OR_WORKSHOP_YOU_CANNOT_DISCARD_DESTROY_OR_TRADE_AN_ITEM(1065),
	
	S1_HP_HAS_BEEN_RESTORED(1066),
	
	S2_HP_HAS_BEEN_RESTORED_BY_C1(1067),
	
	S1_MP_HAS_BEEN_RESTORED(1068),
	
	S2_MP_HAS_BEEN_RESTORED_BY_C1(1069),
	
	THE_BID_AMOUNT_MUST_BE_HIGHER_THAN_THE_PREVIOUS_BID(1075),
	
	YOUR_SELECTED_TARGET_CAN_NO_LONGER_RECEIVE_A_RECOMMENDATION(1188),
	
	YOU_CANNOT_LEAVE_A_CLAN_WHILE_ENGAGED_IN_COMBAT(1116),
	
	A_CLAN_MEMBER_MAY_NOT_BE_DISMISSED_DURING_COMBAT(1117),
	
	PROGRESS_IN_A_QUEST_IS_POSSIBLE_ONLY_WHEN_YOUR_INVENTORYS_WEIGHT_AND_SLOT_COUNT_ARE_LESS_THAN_80_PERCENT_OF_CAPACITY(1118),
	
	A_PRIVATE_STORE_MAY_NOT_BE_OPENED_WHILE_USING_A_SKILL(1128),
	
	WHILE_YOU_ARE_ENGAGED_IN_COMBAT_YOU_CANNOT_OPERATE_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP(1135),
	
	C1_HARVESTED_S3_S2S(1137),
	
	WOULD_YOU_LIKE_TO_OPEN_THE_GATE(1140),
	
	WOULD_YOU_LIKE_TO_CLOSE_THE_GATE(1141),
	
	SINCE_S1_ALREADY_EXISTS_NEARBY_YOU_CANNOT_SUMMON_IT_AGAIN(1142),
	
	SINCE_YOU_DO_NOT_HAVE_ENOUGH_ITEMS_TO_MAINTAIN_THE_SERVITORS_STAY_THE_SERVITOR_HAS_DISAPPEARED(1143),
	
	C1_CREATED_S2_AFTER_RECEIVING_S3_ADENA(1146),
	
	C1_CREATED_S2_S3_AT_THE_PRICE_OF_S4_ADENA(1148),
	
	YOUR_ATTEMPT_TO_CREATE_S2_FOR_C1_AT_THE_PRICE_OF_S3_ADENA_HAS_FAILED(1149),
	
	C1_HAS_FAILED_TO_CREATE_S2_AT_THE_PRICE_OF_S3_ADENA(1150),
	
	S2_IS_SOLD_TO_C1_FOR_THE_PRICE_OF_S3_ADENA(1151),
	
	S2_S3_HAVE_BEEN_SOLD_TO_C1_FOR_S4_ADENA(1152),
	
	S2_HAS_BEEN_PURCHASED_FROM_C1_AT_THE_PRICE_OF_S3_ADENA(1153),
	
	S3_S2_HAS_BEEN_PURCHASED_FROM_C1_FOR_S4_ADENA(1154),
	
	S2S3_HAS_BEEN_SOLD_TO_C1_AT_THE_PRICE_OF_S4_ADENA(1155),
	
	S2S3_HAS_BEEN_PURCHASED_FROM_C1_AT_THE_PRICE_OF_S4_ADENA(1156),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_ARRIVE_AT_GLUDIN_HARBOR_IN_APPROXIMATELY_10_MINUTES(1159),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_BE_ARRIVING_AT_GLUDIN_HARBOR_IN_APPROXIMATELY_5_MINUTES(1160),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_BE_ARRIVING_AT_GLUDIN_HARBOR_IN_APPROXIMATELY_1_MINUTE(1161),
	
	THE_FERRY_FROM_GIRAN_HARBOR_WILL_BE_ARRIVING_AT_TALKING_ISLAND_IN_APPROXIMATELY_15_MINUTES(1162),
	
	THE_FERRY_FROM_GIRAN_HARBOR_WILL_BE_ARRIVING_AT_TALKING_ISLAND_IN_APPROXIMATELY_10_MINUTES(1163),
	
	THE_FERRY_FROM_GIRAN_HARBOR_WILL_BE_ARRIVING_AT_TALKING_ISLAND_IN_APPROXIMATELY_5_MINUTES(1164),
	
	THE_FERRY_FROM_GIRAN_HARBOR_WILL_BE_ARRIVING_AT_TALKING_ISLAND_IN_APPROXIMATELY_1_MINUTE(1165),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_BE_ARRIVING_AT_GIRAN_HARBOR_IN_APPROXIMATELY_20_MINUTES(1166),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_BE_ARRIVING_AT_GIRAN_HARBOR_IN_APPROXIMATELY_15_MINUTES(1167),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_BE_ARRIVING_AT_GIRAN_HARBOR_IN_APPROXIMATELY_10_MINUTES(1168),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_BE_ARRIVING_AT_GIRAN_HARBOR_IN_APPROXIMATELY_5_MINUTES(1169),
	
	THE_FERRY_FROM_TALKING_ISLAND_WILL_BE_ARRIVING_AT_GIRAN_HARBOR_IN_APPROXIMATELY_1_MINUTE(1170),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_ARRIVE_IN_APPROXIMATELY_20_MINUTES(1171),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_ARRIVE_IN_APPROXIMATELY_15_MINUTES(1172),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_ARRIVE_IN_APPROXIMATELY_10_MINUTES(1173),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_ARRIVE_IN_APPROXIMATELY_5_MINUTES(1174),
	
	THE_INNADRIL_PLEASURE_BOAT_WILL_ARRIVE_IN_APPROXIMATELY_1_MINUTE(1175),
	
	THE_TEMPORARY_ALLIANCE_OF_THE_CASTLE_ATTACKER_TEAM_IS_IN_EFFECT(1189),
	
	THE_TEMPORARY_ALLIANCE_OF_THE_CASTLE_ATTACKER_TEAM_HAS_BEEN_DISSOLVED(1190),
	
	A_MERCENARY_CAN_BE_ASSIGNED_TO_A_POSITION_FROM_THE_BEGINNING_OF_THE_SEAL_VALIDATION_PERIOD_UNTIL_THE_TIME_WHEN_A_SIEGE_STARTS(1194),
	
	THIS_MERCENARY_CANNOT_BE_ASSIGNED_TO_A_POSITION_BY_USING_THE_SEAL_OF_STRIFE(1195),
	
	YOUR_FORCE_HAS_REACHED_MAXIMUM_CAPACITY_(1196),
	
	THE_ITEM_HAS_BEEN_SUCCESSFULLY_CRYSTALLIZED(1198),
	
	C1_DIED_AND_DROPPED_S3_S2(1208),
	
	CONGRATULATIONS_YOUR_RAID_WAS_SUCCESSFUL(1209),
	
	C1_HAS_BLOCKED_YOU_YOU_CANNOT_SEND_MAIL_TO_C1(1228),
	
	YOUVE_SENT_MAIL(1231),
	
	THE_MESSAGE_WAS_NOT_SENT(1232),
	
	YOUVE_GOT_MAIL(1233),
	
	C1_HAS_DIED_AND_DROPPED_S2_ADENA(1246),
	
	YOU_ARE_OUT_OF_FEED(1248),
	
	SEVEN_SIGNS_PREPARATIONS_HAVE_BEGUN_FOR_THE_NEXT_QUEST_EVENT(1260),
	
	SEVEN_SIGNS_THE_QUEST_EVENT_PERIOD_HAS_BEGUN(1261),
	
	SEVEN_SIGNS_QUEST_EVENT_HAS_ENDED(1262),
	
	SEVEN_SIGNS_THIS_IS_THE_SEAL_VALIDATION_PERIOD(1263),
	
	THE_NEW_SUBCLASS_S1_HAS_BEEN_ADDED(1269),
	
	YOU_HAVE_SUCCESSFULLY_SWITCHED_TO_YOUR_SUBCLASS(1270),
	
	YOU_WILL_PARTICIPATE_IN_THE_SEVEN_SIGNS_AS_A_MEMBER_OF_THE_LORDS_OF_DAWN(1273),
	
	YOU_WILL_PARTICIPATE_IN_THE_SEVEN_SIGNS_AS_A_MEMBER_OF_THE_REVOLUTIONARIES_OF_DUSK(1274),
	
	YOUVE_CHOSEN_TO_FIGHT_FOR_THE_SEAL_OF_AVARICE_DURING_THIS_QUEST_EVENT_PERIOD(1275),
	
	YOUVE_CHOSEN_TO_FIGHT_FOR_THE_SEAL_OF_GNOSIS_DURING_THIS_QUEST_EVENT_PERIOD(1276),
	
	YOUVE_CHOSEN_TO_FIGHT_FOR_THE_SEAL_OF_STRIFE_DURING_THIS_QUEST_EVENT_PERIOD(1277),
	
	CONTRIBUTION_LEVEL_HAS_EXCEEDED_THE_LIMIT(1279),
	
	MAGIC_CRITICAL_HIT(1280),
	
	YOUR_EXCELLENT_SHIELD_DEFENSE_WAS_A_SUCCESS(1281),
	
	YOUR_FAME_HAS_BEEN_CHANGED_TO_S1(1282),
	
	SUBCLASSES_MAY_NOT_BE_CREATED_OR_CHANGED_WHILE_A_SKILL_IS_IN_USE(1295),
	
	YOU_CANNOT_OPEN_A_PRIVATE_STORE_HERE(1296),
	
	YOU_CANNOT_OPEN_A_PRIVATE_WORKSHOP_HERE(1297),
	
	THIS_MAY_ONLY_BE_USED_DURING_THE_QUEST_EVENT_PERIOD(1303),
	
	YOU_ARE_NO_LONGER_TRYING_ON_EQUIPMENT_(1306),
	
	CONGRATULATIONS__YOUVE_COMPLETED_A_CLASS_TRANSFER(1308),
	
	YOU_ARE_CURRENTLY_BLOCKED_FROM_USING_THE_PRIVATE_STORE_AND_PRIVATE_WORKSHOP(1329),
	
	YOU_ARE_NOT_ALLOWED_TO_CHAT_WITH_A_CONTACT_WHILE_A_CHATTING_BLOCK_IS_IMPOSED(1354),
	
	YOU_HAVE_BEEN_BLOCKED_FROM_CHATTING_WITH_THAT_CONTACT(1357),
	
	YOU_CAN_NOT_TRY_THOSE_ITEMS_ON_AT_THE_SAME_TIME(1368),
	
	YOU_ARE_NOT_ALLOWED_TO_DISMOUNT_IN_THIS_LOCATION(1385),
	
	YOU_HAVE_EXITED_THE_PARTY_ROOM(1391),
	
	C1_HAS_LEFT_THE_PARTY_ROOM(1392),
	
	YOU_HAVE_BEEN_OUSTED_FROM_THE_PARTY_ROOM(1393),
	
	C1_HAS_BEEN_KICKED_FROM_THE_PARTY_ROOM(1394),
	
	THE_PARTY_ROOM_HAS_BEEN_DISBANDED(1395),
	
	THE_LIST_OF_PARTY_ROOMS_CAN_ONLY_BE_VIEWED_BY_A_PERSON_WHO_IS_NOT_PART_OF_A_PARTY(1396),
	
	THE_LEADER_OF_THE_PARTY_ROOM_HAS_CHANGED(1397),
	
	SLOW_DOWN_YOU_ARE_ALREADY_THE_PARTY_LEADER(1401),
	
	YOU_MAY_ONLY_TRANSFER_PARTY_LEADERSHIP_TO_ANOTHER_MEMBER_OF_THE_PARTY(1402),
	
	S1_CP_HAS_BEEN_RESTORED(1405),
	
	S2_CP_HAS_BEEN_RESTORED_BY_C1(1406),
	
	YOU_DO_NOT_MEET_THE_REQUIREMENTS_TO_ENTER_THAT_PARTY_ROOM(1413),
	
	THE_AUTOMATIC_USE_OF_S1_HAS_BEEN_ACTIVATED(1433),
	
	THE_AUTOMATIC_USE_OF_S1_HAS_BEEN_DEACTIVATED(1434),
	
	YOU_DO_NOT_HAVE_ALL_OF_THE_ITEMS_NEEDED_TO_ENCHANT_THAT_SKILL(1439),
	
	YOU_DO_NOT_HAVE_ENOUGH_SP_TO_ENCHANT_THAT_SKILL(1443),
	
	YOUR_PREVIOUS_SUBCLASS_WILL_BE_REMOVED_AND_REPLACED_WITH_THE_NEW_SUBCLASS_AT_LEVEL_40(1445),
	
	YOU_CANNOT_DO_THAT_WHILE_FISHING(1447),
	
	ONLY_FISHING_SKILLS_MAY_BE_USED_AT_THIS_TIME(1448),
	
	YOUVE_GOT_A_BITE(1449),
	
	THAT_FISH_IS_MORE_DETERMINED_THAN_YOU_ARE__IT_SPIT_THE_HOOK(1450),
	
	YOUR_BAIT_WAS_STOLEN_BY_THAT_FISH(1451),
	
	THE_BAIT_HAS_BEEN_LOST_BECAUSE_THE_FISH_GOT_AWAY(1452),
	
	YOU_DO_NOT_HAVE_A_FISHING_POLE_EQUIPPED(1453),
	
	YOU_MUST_PUT_BAIT_ON_YOUR_HOOK_BEFORE_YOU_CAN_FISH(1454),
	
	YOU_CANNOT_FISH_WHILE_UNDER_WATER(1455),
	
	YOU_CANNOT_FISH_WHILE_RIDING_AS_A_PASSENGER_OF_A_BOAT__ITS_AGAINST_THE_RULES(1456),
	
	YOU_CANT_FISH_HERE(1457),
	
	YOUR_ATTEMPT_AT_FISHING_HAS_BEEN_CANCELLED(1458),
	
	YOU_DO_NOT_HAVE_ENOUGH_BAIT(1459),
	
	YOU_REEL_YOUR_LINE_IN_AND_STOP_FISHING(1460),
	
	YOU_CAST_YOUR_LINE_AND_START_TO_FISH(1461),
	
	YOU_MAY_ONLY_USE_THE_PUMPING_SKILL_WHILE_YOU_ARE_FISHING(1462),
	
	YOU_MAY_ONLY_USE_THE_REELING_SKILL_WHILE_YOU_ARE_FISHING(1463),
	
	THE_FISH_HAS_RESISTED_YOUR_ATTEMPT_TO_BRING_IT_IN(1464),
	
	YOU_CAUGHT_SOMETHING(1469),
	
	YOU_CANNOT_DO_THAT_WHILE_FISHING_(1470),
	
	YOU_CANNOT_DO_THAT_WHILE_FISHING_2(1471),
	
	THAT_IS_THE_WRONG_GRADE_OF_SOULSHOT_FOR_THAT_FISHING_POLE(1479),
	
	TRADED_S2_OF_S1_CROPS(1490),
	
	FAILED_IN_TRADING_S2_OF_S1_CROPS(1491),
	
	YOUR_OPPONENT_MADE_HASTE_WITH_THEIR_TAIL_BETWEEN_THEIR_LEGS_THE_MATCH_HAS_BEEN_CANCELLED(1493),
	
	YOUR_OPPONENT_DOES_NOT_MEET_THE_REQUIREMENTS_TO_DO_BATTLE_THE_MATCH_HAS_BEEN_CANCELLED(1494),
	
	THE_MATCH_WILL_START_IN_S1_SECONDS(1495),
	
	THE_MATCH_HAS_STARTED(1496),
	
	CONGRATULATIONS_C1_YOU_WIN_THE_MATCH(1497),
	
	THERE_IS_NO_VICTOR_THE_MATCH_ENDS_IN_A_TIE(1498),
	
	YOU_WILL_BE_MOVED_BACK_TO_TOWN_IN_S1_SECONDS(1499),
	
	C1_DOES_NOT_MEET_THE_PARTICIPATION_REQUIREMENTS_SUBCLASS_CHARACTER_CANNOT_PARTICIPATE_IN_THE_OLYMPIAD(1500),
	
	C1_DOES_NOT_MEET_THE_PARTICIPATION_REQUIREMENTS_ONLY_NOBLESSE_CHARACTERS_CAN_PARTICIPATE_IN_THE_OLYMPIAD(1501),
	
	C1_IS_ALREADY_REGISTERED_ON_THE_MATCH_WAITING_LIST(1502),
	
	YOU_HAVE_BEEN_REGISTERED_FOR_THE_GRAND_OLYMPIAD_WAITING_LIST_FOR_A_CLASS_SPECIFIC_MATCH(1503),
	
	YOU_ARE_CURRENTLY_REGISTERED_FOR_A_1V1_CLASS_IRRELEVANT_MATCH(1504),
	
	YOU_HAVE_BEEN_REMOVED_FROM_THE_GRAND_OLYMPIAD_WAITING_LIST(1505),
	
	YOU_ARE_NOT_CURRENTLY_REGISTERED_FOR_THE_GRAND_OLYMPIAD(1506),
	
	YOU_CANNOT_EQUIP_THAT_ITEM_IN_A_GRAND_OLYMPIAD_MATCH(1507),
	
	YOU_CANNOT_USE_THAT_ITEM_IN_A_GRAND_OLYMPIAD_MATCH(1508),
	
	YOU_CANNOT_USE_THAT_SKILL_IN_A_GRAND_OLYMPIAD_MATCH(1509),
	
	C1_IS_MAKING_AN_ATTEMPT_TO_RESURRECT_YOU_IF_YOU_CHOOSE_THIS_PATH_S2_EXPERIENCE_WILL_BE_RETURNED_FOR_YOU(1510),
	
	WHILE_A_PET_IS_BEING_RESURRECTED_IT_CANNOT_HELP_IN_RESURRECTING_ITS_MASTER(1511),
	
	RESURRECTION_HAS_ALREADY_BEEN_PROPOSED(1513),
	
	A_PET_CANNOT_BE_RESURRECTED_WHILE_ITS_OWNER_IS_IN_THE_PROCESS_OF_RESURRECTING(1515),
	
	THE_TARGET_IS_UNAVAILABLE_FOR_SEEDING(1516),
	
	THE_BLESSED_ENCHANT_FAILED(1517),
	
	YOU_DO_NOT_MEET_THE_REQUIRED_CONDITION_TO_EQUIP_THAT_ITEM(1518),
	
	THE_PET_HAS_BEEN_KILLED(1519),
	
	YOUR_SERVITOR_HAS_VANISHED_YOULL_NEED_TO_SUMMON_A_NEW_ONE(1521),
	
	YOU_SHOULD_RELEASE_YOUR_PET_OR_SERVITOR_SO_THAT_IT_DOES_NOT_FALL_OFF_OF_THE_BOAT_AND_DROWN(1523),
	
	YOUR_PET_WAS_HUNGRY_SO_IT_ATE_S1(1527),
	
	YOUR_CLAN_NOTICE_HAS_BEEN_SAVED(1556),
	
	S1_HAS_DECLARED_A_CLAN_WAR_CLAN_WAR_STARTS_IN_3_DAYS(1561),
	
	YOU_HAVE_DECLARED_A_CLAN_WAR_WITH_S1_CLAN_WAR_STARTS_IN_3_DAYS(1562),
	
	A_CLAN_WAR_CAN_ONLY_BE_DECLARED_IF_THE_CLAN_IS_LEVEL_3_OR_ABOVE_AND_THE_NUMBER_OF_CLAN_MEMBERS_IS_FIFTEEN_OR_GREATER(1564),
	
	A_CLAN_WAR_CANNOT_BE_DECLARED_AGAINST_A_CLAN_THAT_DOES_NOT_EXIST(1565),
	
	THE_CLAN_S1_HAS_DECIDED_TO_STOP_THE_WAR(1566),
	
	THE_WAR_AGAINST_S1_CLAN_HAS_BEEN_STOPPED(1567),
	
	THE_TARGET_FOR_DECLARATION_IS_WRONG(1568),
	
	A_DECLARATION_OF_CLAN_WAR_AGAINST_AN_ALLIED_CLAN_CANT_BE_MADE(1569),
	
	A_DECLARATION_OF_WAR_AGAINST_MORE_THAN_30_CLANS_CANT_BE_MADE_AT_THE_SAME_TIME(1570),
	
	CLANS_YOUVE_DECLARED_WAR_ON(1571),
	
	CLANS_THAT_HAVE_DECLARED_WAR_ON_YOU(1572),
	
	COMMAND_CHANNELS_CAN_ONLY_BE_FORMED_BY_A_PARTY_LEADER_WHO_IS_ALSO_THE_LEADER_OF_A_LEVEL_5_CLAN(1575),
	
	THE_COMMAND_CHANNEL_HAS_BEEN_FORMED(1580),
	
	THE_COMMAND_CHANNEL_HAS_BEEN_DISBANDED(1581),
	
	YOU_WERE_DISMISSED_FROM_THE_COMMAND_CHANNEL(1583),
	
	C1S_PARTY_HAS_BEEN_DISMISSED_FROM_THE_COMMAND_CHANNEL(1584),
	
	YOU_HAVE_QUIT_THE_COMMAND_CHANNEL(1586),
	
	NO_USER_HAS_BEEN_INVITED_TO_THE_COMMAND_CHANNEL(1591),
	
	YOU_CAN_NO_LONGER_SET_UP_A_COMMAND_CHANNEL(1592),
	
	YOU_DO_NOT_HAVE_AUTHORITY_TO_INVITE_SOMEONE_TO_THE_COMMAND_CHANNEL(1593),
	
	C1S_PARTY_IS_ALREADY_A_MEMBER_OF_THE_COMMAND_CHANNEL(1594),
	
	S1_HAS_SUCCEEDED(1595),
	
	S1_HAS_FAILED(1597),
	
	SOULSHOTS_AND_SPIRITSHOTS_ARE_NOT_AVAILABLE_FOR_A_DEAD_PET_OR_SERVITOR(1598),
	
	YOU_CANNOT_OBSERVE_WHILE_YOU_ARE_IN_COMBAT(1599),
	
	ONLY_A_PARTY_LEADER_CAN_ACCESS_THE_COMMAND_CHANNEL(1602),
	
	ONLY_THE_COMMAND_CHANNEL_CREATOR_CAN_USE_THE_RAID_LEADER_TEXT(1603),
	
	_HERE_YOU_CAN_BUY_ONLY_SEEDS_OF_S1_MANOR(1605),
	
	CONGRATULATIONS__YOUVE_COMPLETED_YOUR_THIRDCLASS_TRANSFER_QUEST(1606),
	
	S1_ADENA_HAS_BEEN_WITHDRAWN_TO_PAY_FOR_PURCHASING_FEES(1607),
	
	WAR_HAS_ALREADY_BEEN_DECLARED_AGAINST_THAT_CLAN_BUT_ILL_MAKE_NOTE_THAT_YOU_REALLY_DONT_LIKE_THEM(1609),
	
	FOOL_YOU_CANNOT_DECLARE_WAR_AGAINST_YOUR_OWN_CLAN(1610),
	
	WAR_LIST(1612),
	
	YOU_DO_NOT_HAVE_THE_AUTHORITY_TO_USE_THE_COMMAND_CHANNEL(1617),
	
	THE_FERRY_FROM_RUNE_HARBOR_TO_GLUDIN_HARBOR_HAS_BEEN_DELAYED(1618),
	
	THE_FERRY_FROM_GLUDIN_HARBOR_TO_RUNE_HARBOR_HAS_BEEN_DELAYED(1619),
	
	WELCOME_TO_RUNE_HARBOR(1620),
	
	DEPARTURE_FOR_GLUDIN_HARBOR_WILL_TAKE_PLACE_IN_FIVE_MINUTES(1621),
	
	DEPARTURE_FOR_GLUDIN_HARBOR_WILL_TAKE_PLACE_IN_ONE_MINUTE(1622),
	
	WE_ARE_NOW_DEPARTING_FOR_GLUDIN_HARBOR_HOLD_ON_AND_ENJOY_THE_RIDE(1624),
	
	DEPARTURE_FOR_RUNE_HARBOR_WILL_TAKE_PLACE_AFTER_ANCHORING_FOR_TEN_MINUTES(1625),
	
	DEPARTURE_FOR_RUNE_HARBOR_WILL_TAKE_PLACE_IN_FIVE_MINUTES(1626),
	
	DEPARTURE_FOR_RUNE_HARBOR_WILL_TAKE_PLACE_IN_ONE_MINUTE(1627),
	
	MAKE_HASTE__WE_WILL_BE_DEPARTING_FOR_GLUDIN_HARBOR_SHORTLY(1628),
	
	WE_ARE_NOW_DEPARTING_FOR_RUNE_HARBOR_HOLD_ON_AND_ENJOY_THE_RIDE(1629),
	
	THE_FERRY_FROM_RUNE_HARBOR_WILL_BE_ARRIVING_AT_GLUDIN_HARBOR_IN_APPROXIMATELY_15_MINUTES(1630),
	
	THE_FERRY_FROM_RUNE_HARBOR_WILL_BE_ARRIVING_AT_GLUDIN_HARBOR_IN_APPROXIMATELY_10_MINUTES(1631),
	
	THE_FERRY_FROM_RUNE_HARBOR_WILL_BE_ARRIVING_AT_GLUDIN_HARBOR_IN_APPROXIMATELY_5_MINUTES(1632),
	
	THE_FERRY_FROM_RUNE_HARBOR_WILL_BE_ARRIVING_AT_GLUDIN_HARBOR_IN_APPROXIMATELY_1_MINUTE(1633),
	
	THE_FERRY_FROM_GLUDIN_HARBOR_WILL_BE_ARRIVING_AT_RUNE_HARBOR_IN_APPROXIMATELY_15_MINUTES(1634),
	
	THE_FERRY_FROM_GLUDIN_HARBOR_WILL_BE_ARRIVING_AT_RUNE_HARBOR_IN_APPROXIMATELY_10_MINUTES(1635),
	
	THE_FERRY_FROM_GLUDIN_HARBOR_WILL_BE_ARRIVING_AT_RUNE_HARBOR_IN_APPROXIMATELY_5_MINUTES(1636),
	
	THE_FERRY_FROM_GLUDIN_HARBOR_WILL_BE_ARRIVING_AT_RUNE_HARBOR_IN_APPROXIMATELY_1_MINUTE(1637),
	
	YOU_CANNOT_FISH_WHILE_USING_A_RECIPE_BOOK_PRIVATE_MANUFACTURE_OR_PRIVATE_STORE(1638),
	
	SHARPEN_YOUR_SWORDS_TIGHTEN_THE_STITCHING_IN_YOUR_ARMOR_AND_MAKE_HASTE_TO_A_GRAND_OLYMPIAD_MANAGER__BATTLES_IN_THE_GRAND_OLYMPIAD_GAMES_ARE_NOW_TAKING_PLACE(1641),
	
	MUCH_CARNAGE_HAS_BEEN_LEFT_FOR_THE_CLEANUP_CREW_OF_THE_OLYMPIAD_STADIUM(1642),
	
	THE_GRAND_OLYMPIAD_GAMES_ARE_NOT_CURRENTLY_IN_PROGRESS(1651),
	
	YOU_CAUGHT_SOMETHING_SMELLY_AND_SCARY_MAYBE_YOU_SHOULD_THROW_IT_BACK(1655),
	
	C1_HAS_EARNED_S2_POINTS_IN_THE_GRAND_OLYMPIAD_GAMES(1657),
	
	C1_HAS_LOST_S2_POINTS_IN_THE_GRAND_OLYMPIAD_GAMES(1658),
	
	THE_CLAN_CREST_WAS_SUCCESSFULLY_REGISTERED(1663),
	
	LETHAL_STRIKE(1667),
	
	YOUR_LETHAL_STRIKE_WAS_SUCCESSFUL(1668),
	
	THERE_WAS_NOTHING_FOUND_INSIDE(1669),
	
	DUE_TO_YOUR_REELING_ANDOR_PUMPING_SKILL_BEING_THREE_OR_MORE_LEVELS_HIGHER_THAN_YOUR_FISHING_SKILL_A_50_DAMAGE_PENALTY_WILL_BE_APPLIED(1670),
	
	FOR_THE_CURRENT_GRAND_OLYMPIAD_YOU_HAVE_PARTICIPATED_IN_S1_MATCHES_S2_WINS_S3_DEFEATS_YOU_CURRENTLY_HAVE_S4_OLYMPIAD_POINTS(1673),
	
	THIS_COMMAND_CAN_ONLY_BE_USED_BY_A_NOBLESSE(1674),
	
	A_MANOR_CANNOT_BE_SET_UP_BETWEEN_430_AM_AND_8_PM(1675),
	
	A_CEASEFIRE_DURING_A_CLAN_WAR_CAN_NOT_BE_CALLED_WHILE_MEMBERS_OF_YOUR_CLAN_ARE_ENGAGED_IN_BATTLE(1677),
	
	YOU_HAVE_NOT_DECLARED_A_CLAN_WAR_AGAINST_THE_CLAN_S1(1678),
	
	ONLY_THE_CREATOR_OF_A_COMMAND_CHANNEL_CAN_ISSUE_A_GLOBAL_COMMAND(1679),
	
	C1_HAS_DECLINED_THE_CHANNEL_INVITATION(1680),
	
	ONLY_THE_CREATOR_OF_A_COMMAND_CHANNEL_CAN_USE_THE_CHANNEL_DISMISS_COMMAND(1682),
	
	ONLY_A_PARTY_LEADER_CAN_LEAVE_A_COMMAND_CHANNEL(1683),
	
	THIS_AREA_CANNOT_BE_ENTERED_WHILE_MOUNTED_ATOP_OF_A_WYVERN(1687),
	
	YOU_CANNOT_ENCHANT_WHILE_OPERATING_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP(1688),
	
	C1_IS_ALREADY_REGISTERED_ON_THE_CLASS_MATCH_WAITING_LIST(1689),
	
	C1_IS_ALREADY_REGISTERED_ON_THE_WAITING_LIST_FOR_THE_CLASS_IRRELEVANT_INDIVIDUAL_MATCH(1690),
	
	YOU_MAY_NOT_OBSERVE_A_GRAND_OLYMPIAD_GAMES_MATCH_WHILE_YOU_ARE_ON_THE_WAITING_LIST(1693),
	
	ONLY_A_CLAN_LEADER_THAT_IS_A_NOBLESSE_CAN_VIEW_THE_SIEGE_WAR_STATUS_WINDOW_DURING_A_SIEGE_WAR(1694),
	
	YOU_CANNOT_DISMISS_A_PARTY_MEMBER_BY_FORCE(1699),
	
	YOU_DONT_HAVE_ENOUGH_SPIRITSHOTS_NEEDED_FOR_A_PETSERVITOR(1700),
	
	YOU_DONT_HAVE_ENOUGH_SOULSHOTS_NEEDED_FOR_A_PETSERVITOR(1701),
	
	YOU_ARE_SHORT_OF_ACCUMULATED_POINTS(1710),
	
	YOU_CANNOT_JOIN_A_COMMAND_CHANNEL_WHILE_TELEPORTING(1729),
	
	TO_JOIN_A_CLAN_ACADEMY_CHARACTERS_MUST_BE_LEVEL_40_OR_BELOW_NOT_BELONG_ANOTHER_CLAN_AND_NOT_YET_COMPLETED_THEIR_2ND_CLASS_TRANSFER(1734),
	
	YOUR_CLAN_HAS_ALREADY_ESTABLISHED_A_CLAN_ACADEMY(1738),
	
	CLAN_ACADEMY_MEMBER_S1_HAS_SUCCESSFULLY_AWAKENED_OBTAINING_S2_CLAN_REPUTATION(1748),
	
	CONGRATULATIONS_YOU_WILL_NOW_GRADUATE_FROM_THE_CLAN_ACADEMY_AND_LEAVE_YOUR_CURRENT_CLAN(1749),
	
	S2_HAS_BEEN_DESIGNATED_AS_THE_APPRENTICE_OF_CLAN_MEMBER_S1(1755),
	
	YOUR_APPRENTICE_C1_HAS_LOGGED_IN(1756),
	
	YOUR_APPRENTICE_C1_HAS_LOGGED_OUT(1757),
	
	YOUR_SPONSOR_C1_HAS_LOGGED_IN(1758),
	
	YOUR_SPONSOR_C1_HAS_LOGGED_OUT(1759),
	
	S2_CLAN_MEMBER_C1S_APPRENTICE_HAS_BEEN_REMOVED(1763),
	
	THIS_ITEM_CAN_ONLY_BE_WORN_BY_A_MEMBER_OF_THE_CLAN_ACADEMY(1764),
	
	SINCE_YOUR_CLAN_EMERGED_VICTORIOUS_FROM_THE_SIEGE_S1_POINTS_HAVE_BEEN_ADDED_TO_YOUR_CLANS_REPUTATION_SCORE(1773),
	
	NOW_THAT_YOUR_CLAN_LEVEL_IS_ABOVE_LEVEL_5_IT_CAN_ACCUMULATE_CLAN_REPUTATION_POINTS(1771),
	
	YOUR_CLAN_HAS_FAILED_TO_DEFEND_THE_CASTLE_S1_POINTS_HAVE_BEEN_DEDUCTED_FROM_YOU_CLAN_REPUTATION_SCORE_AND_ADDED_TO_YOUR_OPPONENTS(1784),
	
	S1_POINTS_HAVE_BEEN_DEDUCTED_FROM_THE_CLANS_REPUTATION(1787),
	
	THE_CLAN_SKILL_S1_HAS_BEEN_ADDED(1788),
	
	SINCE_THE_CLAN_REPUTATION_SCORE_HAS_DROPPED_TO_0_OR_LOWER_YOUR_CLAN_SKILLS_WILL_BE_DEACTIVATED(1789),
	
	THE_CONDITIONS_NECESSARY_TO_CREATE_A_MILITARY_UNIT_HAVE_NOT_BEEN_MET(1791),
	
	THE_ATTEMPT_TO_SELL_HAS_FAILED(1801),
	
	THE_ATTEMPT_TO_TRADE_HAS_FAILED(1802),
	
	THE_REGISTRATION_PERIOD_FOR_A_CLAN_HALL_WAR_HAS_ENDED(1823),
	
	YOU_HAVE_BEEN_REGISTERED_FOR_A_CLAN_HALL_WAR(1824),
	
	YOU_HAVE_FAILED_IN_YOUR_ATTEMPT_TO_REGISTER_FOR_THE_CLAN_HALL_WAR(1825),
	
	IN_S1_MINUTES_THE_GAME_WILL_BEGIN_ALL_PLAYERS_MUST_HURRY_AND_MOVE_TO_THE_LEFT_SIDE_OF_THE_CLAN_HALLS_ARENA(1826),
	
	IN_S1_MINUTES_THE_GAME_WILL_BEGIN_ALL_PLAYERS_PLEASE_ENTER_THE_ARENA_NOW(1827),
	
	IN_S1_SECONDS_THE_GAME_WILL_BEGIN(1828),
	
	C1_IS_NOT_ALLOWED_TO_USE_THE_PARTY_ROOM_INVITE_COMMAND(1830),
	
	C1_DOES_NOT_MEET_THE_CONDITIONS_OF_THE_PARTY_ROOM(1831),
	
	ONLY_A_ROOM_LEADER_MAY_INVITE_OTHERS_TO_A_PARTY_ROOM(1832),
	
	THE_PARTY_ROOM_IS_FULL(1834),
	
	S1_IS_FULL_AND_CANNOT_ACCEPT_ADDITIONAL_CLAN_MEMBERS_AT_THIS_TIME(1835),
	
	THIS_CLAN_HALL_WAR_HAS_BEEN_CANCELLED(1841),
	
	C1_WISHES_TO_SUMMON_YOU_FROM_S2(1842),
	
	C1_IS_ENGAGED_IN_COMBAT_AND_CANNOT_BE_SUMMONED(1843),
	
	C1_IS_DEAD_AT_THE_MOMENT_AND_CANNOT_BE_SUMMONED(1844),
	
	HERO_WEAPONS_CANNOT_BE_DESTROYED(1845),
	
	ANOTHER_MILITARY_UNIT_IS_ALREADY_USING_THAT_NAME_PLEASE_ENTER_A_DIFFERENT_NAME(1855),
	
	THE_CLAN_REPUTATION_SCORE_IS_TOO_LOW(1860),
	
	THE_CLAN_MARK_HAS_BEEN_DELETED(1861),
	
	CLAN_SKILLS_WILL_NOW_BE_ACTIVATED_SINCE_THE_CLANS_REPUTATION_SCORE_IS_0_OR_HIGHER(1862),
	
	YOUR_PETSERVITOR_IS_UNRESPONSIVE_AND_WILL_NOT_OBEY_ANY_ORDERS(1864),
	
	THE_PRELIMINARY_MATCH_WILL_BEGIN_IN_S1_SECONDS(1881),
	
	THERE_ARE_NO_OFFERINGS_I_OWN_OR_I_MADE_A_BID_FOR(1883),
	
	YOU_MAY_NOT_USE_ITEMS_IN_A_PRIVATE_STORE_OR_PRIVATE_WORK_SHOP(1891),
	
	A_SUBCLASS_CANNOT_BE_CREATED_OR_CHANGED_WHILE_YOU_ARE_OVER_YOUR_WEIGHT_LIMIT(1894),
	
	C1_IS_CURRENTLY_TRADING_OR_OPERATING_A_PRIVATE_STORE_AND_CANNOT_BE_SUMMONED(1898),
	
	YOUR_TARGET_IS_IN_AN_AREA_WHICH_BLOCKS_SUMMONING(1899),
	
	C1_HAS_ENTERED_THE_PARTY_ROOM(1900),
	
	S1_HAS_SENT_AN_INVITATION_TO_ROOM_S2(1901),
	
	INCOMPATIBLE_ITEM_GRADE(1902),
	
	A_SUBCLASS_MAY_NOT_BE_CREATED_OR_CHANGED_WHILE_A_SERVITOR_OR_PET_IS_SUMMONED(1904),
	
	YOU_CANNOT_SUMMON_PLAYERS_WHO_ARE_CURRENTLY_PARTICIPATING_IN_THE_GRAND_OLYMPIAD(1911),
	
	YOUR_PET_IS_TOO_HIGH_LEVEL_TO_CONTROL(1918),
	
	COURT_MAGICIAN_THE_PORTAL_HAS_BEEN_CREATED(1923),
	
	THERE_IS_NO_OPPONENT_TO_RECEIVE_YOUR_CHALLENGE_FOR_A_DUEL(1926),
	
	C1_HAS_BEEN_CHALLENGED_TO_A_DUEL(1927),
	
	C1S_PARTY_HAS_BEEN_CHALLENGED_TO_A_DUEL(1928),
	
	C1_HAS_ACCEPTED_YOUR_CHALLENGE_TO_A_DUEL(1929),
	
	YOU_HAVE_ACCEPTED_C1S_CHALLENGE_A_DUEL(1930),
	
	C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL(1931),
	
	C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL_(1932),
	
	YOU_HAVE_ACCEPTED_C1S_CHALLENGE_TO_A_PARTY_DUEL(1933),
	
	S1_HAS_ACCEPTED_YOUR_CHALLENGE_TO_DUEL_AGAINST_THEIR_PARTY(1934),
	
	C1_HAS_DECLINED_YOUR_CHALLENGE_TO_A_PARTY_DUEL(1935),
	
	THE_OPPOSING_PARTY_HAS_DECLINED_YOUR_CHALLENGE_TO_A_DUEL(1936),
	
	SINCE_THE_PERSON_YOU_CHALLENGED_IS_NOT_CURRENTLY_IN_A_PARTY_THEY_CANNOT_DUEL_AGAINST_YOUR_PARTY(1937),
	
	C1_HAS_CHALLENGED_YOU_TO_A_DUEL(1938),
	
	C1S_PARTY_HAS_CHALLENGED_YOUR_PARTY_TO_A_DUEL(1939),
	
	YOU_ARE_UNABLE_TO_REQUEST_A_DUEL_AT_THIS_TIME(1940),
	
	IN_A_MOMENT_YOU_WILL_BE_TRANSPORTED_TO_THE_SITE_WHERE_THE_DUEL_WILL_TAKE_PLACE(1944),
	
	THE_DUEL_WILL_BEGIN_IN_S1_SECONDS(1945),
	
	LET_THE_DUEL_BEGIN(1949),
	
	C1_HAS_WON_THE_DUEL(1950),
	
	C1S_PARTY_HAS_WON_THE_DUEL(1951),
	
	THE_DUEL_HAS_ENDED_IN_A_TIE(1952),
	
	SELECT_THE_ITEM_TO_BE_AUGMENTED(1957),
	
	SELECT_THE_CATALYST_FOR_AUGMENTATION(1958),
	
	THIS_IS_NOT_A_SUITABLE_ITEM(1960),
	
	GEMSTONE_QUANTITY_IS_INCORRECT(1961),
	
	THE_ITEM_WAS_SUCCESSFULLY_AUGMENTED(1962),
	
	SELECT_THE_ITEM_FROM_WHICH_YOU_WISH_TO_REMOVE_AUGMENTATION(1963),
	
	AUGMENTATION_REMOVAL_CAN_ONLY_BE_DONE_ON_AN_AUGMENTED_ITEM(1964),
	
	AUGMENTATION_HAS_BEEN_SUCCESSFULLY_REMOVED_FROM_YOUR_S1(1965),
	
	ONLY_THE_CLAN_LEADER_MAY_ISSUE_COMMANDS(1966),
	
	ONCE_AN_ITEM_IS_AUGMENTED_IT_CANNOT_BE_AUGMENTED_AGAIN(1970),
	
	YOU_CANNOT_AUGMENT_ITEMS_WHILE_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP_IS_IN_OPERATION(1972),
	
	YOU_CANNOT_AUGMENT_ITEMS_WHILE_DEAD(1974),
	
	YOU_CANNOT_AUGMENT_ITEMS_WHILE_PARALYZED(1976),
	
	YOU_CANNOT_AUGMENT_ITEMS_WHILE_FISHING(1977),
	
	YOU_CANNOT_AUGMENT_ITEMS_WHILE_SITTING_DOWN(1978),
	
	S1(1983),
	
	PRESS_THE_AUGMENT_BUTTON_TO_BEGIN(1984),
	
	THE_FERRY_HAS_ARRIVED_AT_PRIMEVAL_ISLE(1988),
	
	THE_FERRY_WILL_LEAVE_FOR_RUNE_HARBOR_AFTER_ANCHORING_FOR_THREE_MINUTES(1989),
	
	YOUR_DEATH_PENALTY_HAS_BEEN_LIFTED(1917),
	
	THE_FERRY_IS_NOW_DEPARTING_PRIMEVAL_ISLE_FOR_RUNE_HARBOR(1990),
	
	THE_FERRY_WILL_LEAVE_FOR_PRIMEVAL_ISLE_AFTER_ANCHORING_FOR_THREE_MINUTES(1991),
	
	THE_FERRY_IS_NOW_DEPARTING_RUNE_HARBOR_FOR_PRIMEVAL_ISLE(1992),
	
	THE_FERRY_FROM_PRIMEVAL_ISLE_TO_RUNE_HARBOR_HAS_BEEN_DELAYED(1993),
	
	THE_FERRY_FROM_RUNE_HARBOR_TO_PRIMEVAL_ISLE_HAS_BEEN_DELAYED(1994),
	
	THE_ATTACK_HAS_BEEN_BLOCKED(1996),
	
	C1_IS_PERFORMING_A_COUNTERATTACK(1997),
	
	AUGMENTATION_FAILED_DUE_TO_INAPPROPRIATE_CONDITIONS(2001),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_ENGAGED_IN_A_PRIVATE_STORE_OR_MANUFACTURE(2017),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_FISHING(2018),
	
	C1_CANNOT_DUEL_BECAUSE_C1S_HP_OR_MP_IS_BELOW_50(2019),
	
	C1_CANNOT_MAKE_A_CHALLENGE_TO_A_DUEL_BECAUSE_C1_IS_CURRENTLY_IN_A_DUELPROHIBITED_AREA_PEACEFUL_ZONE__SEVEN_SIGNS_ZONE__NEAR_WATER__RESTART_PROHIBITED_AREA(2020),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_ENGAGED_IN_BATTLE(2021),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_ALREADY_ENGAGED_IN_A_DUEL(2022),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_IN_A_CHAOTIC_STATE(2023),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_THE_OLYMPIAD(2024),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_A_CLAN_HALL_WAR(2025),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_PARTICIPATING_IN_A_SIEGE_WAR(2026),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_RIDING_A_BOAT_STEED_OR_STRIDER(2027),
	
	C1_CANNOT_RECEIVE_A_DUEL_CHALLENGE_BECAUSE_C1_IS_TOO_FAR_AWAY(2028),
	
	A_SUBCLASS_CANNOT_BE_CREATED_OR_CHANGED_BECAUSE_YOU_HAVE_EXCEEDED_YOUR_INVENTORY_LIMIT(2033),
	
	SOME_LINEAGE_II_FEATURES_HAVE_BEEN_LIMITED_FOR_FREE_TRIALS_(2039),
	
	SOME_LINEAGE_II_FEATURES_HAVE_BEEN_LIMITED_FOR_FREE_TRIALS_____(2046),
	
	S1_CLAN_IS_TRYING_TO_DISPLAY_A_FLAG(2050),
	
	YOU_HAVE_BLOCKED_C1(2057),
	
	YOU_ALREADY_POLYMORPHED_AND_CANNOT_POLYMORPH_AGAIN(2058),
	
	YOU_CANNOT_POLYMORPH_INTO_THE_DESIRED_FORM_IN_WATER(2060),
	
	YOU_CANNOT_POLYMORPH_WHEN_YOU_HAVE_SUMMONED_A_SERVITORPET(2062),
	
	YOU_CANNOT_POLYMORPH_WHILE_RIDING_A_PET(2063),
	
	YOU_CANNOT_POLYMORPH_WHILE_UNDER_THE_EFFECT_OF_A_SPECIAL_SKILL(2064),
	
	THAT_WEAPON_CANNOT_PERFORM_ANY_ATTACKS(2066),
	
	THAT_WEAPON_CANNOT_USE_ANY_OTHER_SKILL_EXCEPT_THE_WEAPONS_SKILL(2067),
	
	UNTRAIN_OF_ENCHANT_SKILL_WAS_SUCCESSFUL_CURRENT_LEVEL_OF_ENCHANT_SKILL_S1_HAS_BEEN_DECREASED_BY_1(2069),
	
	UNTRAIN_OF_ENCHANT_SKILL_WAS_SUCCESSFUL_CURRENT_LEVEL_OF_ENCHANT_SKILL_S1_BECAME_0_AND_ENCHANT_SKILL_WILL_BE_INITIALIZED(2070),
	
	IT_IS_NOT_AN_AUCTION_PERIOD(2075),
	
	BIDDING_IS_NOT_ALLOWED_BECAUSE_THE_MAXIMUM_BIDDING_PRICE_EXCEEDS_100_BILLION(2076),
	
	YOUR_BID_MUST_BE_HIGHER_THAN_THE_CURRENT_HIGHEST_BID(2077),
	
	YOU_DO_NOT_HAVE_ENOUGH_ADENA_FOR_THIS_BID(2078),
	
	YOU_HAVE_BEEN_OUTBID(2080),
	
	THERE_ARE_NO_FUNDS_PRESENTLY_DUE_TO_YOU(2081),
	
	ENEMY_BLOOD_PLEDGES_HAVE_INTRUDED_INTO_THE_FORTRESS(2084),
	
	SHOUT_AND_TRADE_CHATTING_CANNOT_BE_USED_WHILE_POSSESSING_A_CURSED_WEAPON(2085),
	
	SEARCH_ON_USER_C2_FOR_THIRDPARTY_PROGRAM_USE_WILL_BE_COMPLETED_IN_S1_MINUTES(2086),
	
	A_FORTRESS_IS_UNDER_ATTACK(2087),
	
	S1_MINUTES_UNTIL_THE_FORTRESS_BATTLE_STARTS(2088),
	
	S1_SECONDS_UNTIL_THE_FORTRESS_BATTLE_STARTS(2089),
	
	THE_FORTRESS_BATTLE_S1_HAS_BEGUN(2090),
	
	C1_IS_IN_A_LOCATION_WHICH_CANNOT_BE_ENTERED_THEREFORE_IT_CANNOT_BE_PROCESSED(2096),
	
	C1S_LEVEL_DOES_NOT_CORRESPOND_TO_THE_REQUIREMENTS_FOR_ENTRY(2097),
	
	C1S_QUEST_REQUIREMENT_IS_NOT_SUFFICIENT_AND_CANNOT_BE_ENTERED(2098),
	
	C1S_ITEM_REQUIREMENT_IS_NOT_SUFFICIENT_AND_CANNOT_BE_ENTERED(2099),
	
	C1_MAY_NOT_REENTER_YET(2100),
	
	YOU_ARE_NOT_CURRENTLY_IN_A_PARTY_SO_YOU_CANNOT_ENTER(2101),
	
	YOU_CANNOT_ENTER_DUE_TO_THE_PARTY_HAVING_EXCEEDED_THE_LIMIT(2102),
	
	YOU_CANNOT_ENTER_BECAUSE_YOU_ARE_NOT_ASSOCIATED_WITH_THE_CURRENT_COMMAND_CHANNEL(2103),
	
	THE_MAXIMUM_NUMBER_OF_INSTANCE_ZONES_HAS_BEEN_EXCEEDED(2104),
	
	YOU_HAVE_ENTERED_ANOTHER_INSTANCE_ZONE_THEREFORE_YOU_CANNOT_ENTER_CORRESPONDING_DUNGEON(2105),
	
	THIS_DUNGEON_WILL_EXPIRE_IN_S1_MINUTES(2106),
	
	YOU_CANNOT_CONVERT_THIS_ITEM(2130),
	
	YOU_HAVE_BID_THE_HIGHEST_PRICE_AND_HAVE_WON_THE_ITEM(2131),
	
	YOU_CANNOT_ADD_ELEMENTAL_POWER_WHILE_OPERATING_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP(2143),
	
	PLEASE_SELECT_ITEM_TO_ADD_ELEMENTAL_POWER(2144),
	
	ATTRIBUTE_ITEM_USAGE_HAS_BEEN_CANCELLED(2145),
	
	YOU_HAVE_FAILED_TO_ADD_ELEMENTAL_POWER(2149),
	
	ANOTHER_ELEMENTAL_POWER_HAS_ALREADY_BEEN_ADDED(2150),
	
	YOUR_OPPONENT_HAS_RESISTANCE_TO_MAGIC_THE_DAMAGE_WAS_DECREASED(2151),
	
	THE_TARGET_IS_NOT_A_FLAGPOLE_SO_A_FLAG_CANNOT_BE_DISPLAYED(2154),
	
	A_FLAG_IS_ALREADY_BEING_DISPLAYED_ANOTHER_FLAG_CANNOT_BE_DISPLAYED(2155),
	
	THERE_ARE_NOT_ENOUGH_NECESSARY_ITEMS_TO_USE_THE_SKILL(2156),
	
	FORCE_ATTACK_IS_IMPOSSIBLE_AGAINST_A_TEMPORARY_ALLIED_MEMBER_DURING_A_SIEGE(2158),
	
	BIDDER_EXISTS_THE_AUCTION_TIME_HAS_BEEN_EXTENDED_BY_5_MINUTES(2159),
	
	BIDDER_EXISTS_AUCTION_TIME_HAS_BEEN_EXTENDED_BY_3_MINUTES(2160),
	
	THERE_IS_NOT_ENOUGH_SPACE_TO_MOVE_THE_SKILL_CANNOT_BE_USED(2161),
	
	THE_BARRACKS_HAVE_BEEN_SEIZED(2164),
	
	THE_BARRACKS_FUNCTION_HAS_BEEN_RESTORED(2165),
	
	ALL_BARRACKS_ARE_OCCUPIED(2166),
	
	A_MALICIOUS_SKILL_CANNOT_BE_USED_IN_A_PEACE_ZONE(2167),
	
	C1_HAS_ACQUIRED_THE_FLAG(2168),
	
	YOUR_CLAN_HAS_BEEN_REGISTERED_TO_S1S_FORTRESS_BATTLE(2169),
	
	THIS_ITEM_CANNOT_BE_CRYSTALLIZED(2171),
	
	C1_CANNOT_DUEL_BECAUSE_C1_IS_CURRENTLY_POLYMORPHED(2174),
	
	PARTY_DUEL_CANNOT_BE_INITIATED_DUE_TO_A_POLYMORPHED_PARTY_MEMBER(2175),
	
	YOU_CANNOT_POLYMORPH_WHILE_RIDING_A_BOAT(2182),
	
	THE_FORTRESS_BATTLE_OF_S1_HAS_FINISHED(2183),
	
	S1_IS_VICTORIOUS_IN_THE_FORTRESS_BATTLE_OF_S2(2184),
	
	ONLY_A_PARTY_LEADER_CAN_MAKE_THE_REQUEST_TO_ENTER(2185),
	
	SOUL_CANNOT_BE_ABSORBED_ANYMORE(2186),
	
	THE_TARGET_IS_LOCATED_WHERE_YOU_CANNOT_CHARGE(2187),
	
	YOU_ARE_TOO_FAR_FROM_THE_NPC_FOR_THAT_TO_WORK(2193),
	
	YOU_DO_NOT_HAVE_ENOUGH_SOULS(2195),
	
	THIS_IS_AN_AREA_WHERE_YOU_CANNOT_USE_THE_MINI_MAP(2207),
	
	YOU_CANNOT_BOARD_A_SHIP_WHILE_YOU_ARE_POLYMORPHED(2213),
	
	THE_BALLISTA_HAS_BEEN_SUCCESSFULLY_DESTROYED(2217),
	
	THIS_SQUAD_SKILL_HAS_ALREADY_BEEN_ACQUIRED(2219),
	
	THE_PREVIOUS_LEVEL_SKILL_HAS_NOT_BEEN_LEARNED(2220),
	
	NOT_ENOUGH_BOLTS(2226),
	
	IT_IS_NOT_POSSIBLE_TO_REGISTER_FOR_THE_CASTLE_SIEGE_SIDE_OR_CASTLE_SIEGE_OF_A_HIGHER_CASTLE_IN_THE_CONTRACT(2227),
	
	INSTANCE_ZONE_TIME_LIMIT(2228),
	
	THERE_IS_NO_INSTANCE_ZONE_UNDER_A_TIME_LIMIT(2229),
	
	S1_WILL_BE_AVAILABLE_FOR_REUSE_AFTER_S2_HOURS_S3_MINUTES(2230),
	
	SIEGE_REGISTRATION_IS_NOT_POSSIBLE_DUE_TO_YOUR_CASTLE_CONTRACT(2233),
	
	YOU_ARE_PARTICIPATING_IN_THE_SIEGE_OF_S1_THIS_SIEGE_IS_SCHEDULED_FOR_2_HOURS(2238),
	
	S1_MINUTES_REMAINING(2244),
	
	S1_SECONDS_REMAINING(2245),
	
	THE_CONTEST_WILL_BEGIN_IN_S1_MINUTES(2246),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_TRANSFORMED(2247),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_PETRIFIED(2248),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_DEAD(2249),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_FISHING(2250),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_IN_BATTLE(2251),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_IN_A_DUEL(2252),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_SITTING(2253),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_CASTING(2254),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHEN_A_CURSED_WEAPON_IS_EQUIPPED(2255),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_HOLDING_A_FLAG(2256),
	
	YOU_CANNOT_BOARD_AN_AIRSHIP_WHILE_A_PET_OR_A_SERVITOR_IS_SUMMONED(2257),
	
	YOU_HAVE_ALREADY_BOARDED_ANOTHER_AIRSHIP(2258),
	
	YOUR_PETS_HUNGER_GAUGE_IS_BELOW_10(2260),
	
	C1_HAS_DONE_S3_POINTS_OF_DAMAGE_TO_C2(2261),
	
	C1_HAS_RECEIVED_S3_DAMAGE_FROM_C2(2262),
	
	C1_HAS_EVADED_C2S_ATTACK(2264),
	
	C1S_ATTACK_WENT_ASTRAY(2265),
	
	C1_RESISTED_C2S_MAGIC(2269),
	
	THIS_SKILL_CANNOT_BE_LEARNED_WHILE_IN_THE_SUBCLASS_STATE(2273),
	
	DAMAGE_IS_DECREASED_BECAUSE_C1_RESISTED_C2S_MAGIC(2280),
	
	C1_INFLICTED_S3_DAMAGE_ON_C2_AND_S4_DAMAGE_ON_THE_DAMAGE_TRANSFER_TARGET(2281),
	
	YOU_CANNOT_TRANSFORM_WHILE_SITTING(2283),
	
	YOU_CANNOT_WEAR_S1_BECAUSE_YOU_ARE_NOT_WEARING_A_BRACELET(2286),
	
	YOU_CANNOT_EQUIP_S1_BECAUSE_YOU_DO_NOT_HAVE_ANY_AVAILABLE_SLOTS(2287),
	
	AGATHION_SKILLS_CAN_BE_USED_ONLY_WHEN_YOUR_AGATHION_IS_SUMMONED(2292),
	
	THERE_ARE_S2_SECONDS_REMAINING_IN_S1S_REUSE_TIME(2303),
	
	THERE_ARE_S2_MINUTES_S3_SECONDS_REMAINING_IN_S1S_REUSE_TIME(2304),
	
	THERE_ARE_S2_HOURS_S3_MINUTES_AND_S4_SECONDS_REMAINING_IN_S1S_REUSE_TIME(2305),
	
	YOUR_CHARM_OF_COURAGE_IS_TRYING_TO_RESURRECT_YOU(2306),
	
	YOU_DO_NOT_HAVE_A_SERVITOR(2311),
	
	YOUR_VITALITY_IS_AT_MAXIMUM(2314),
	
	YOUR_VITALITY_HAS_INCREASED(2315),
	
	YOUR_VITALITY_HAS_DECREASED(2316),
	
	YOUR_VITALITY_IS_FULLY_EXHAUSTED(2317),
	
	YOU_HAVE_ACQUIRED_50_CLAN_FAME_POINTS(2326),
	
	YOU_DONT_HAVE_ENOUGH_REPUTATION_TO_DO_THAT(2327),
	
	ONLY_CLANS_WHO_ARE_LEVEL_4_OR_ABOVE_CAN_REGISTER_FOR_BATTLE_AT_DEVASTATED_CASTLE_AND_FORTRESS_OF_THE_DEAD(2328),
	
	YOU_CANNOT_RECEIVE_THE_VITAMIN_ITEM_BECAUSE_YOU_HAVE_EXCEED_YOUR_INVENTORY_WEIGHTQUANTITY_LIMIT(2333),
	
	THERE_ARE_NO_MORE_VITAMIN_ITEMS_TO_BE_FOUND(2335),
	
	CP_SIPHON(2336),
	
	YOUR_CP_WAS_DRAINED_BECAUSE_YOU_WERE_HIT_WITH_A_CP_SIPHON_SKILL(2337),
	
	S1_SECONDS_TO_GAME_END(2347),
	
	YOU_CANNOT_USE_MY_TELEPORTS_DURING_A_BATTLE(2348),
	
	YOU_CANNOT_USE_MY_TELEPORTS_WHILE_PARTICIPATING_A_LARGESCALE_BATTLE_SUCH_AS_A_CASTLE_SIEGE_FORTRESS_SIEGE_OR_HIDEOUT_SIEGE(2349),
	
	YOU_CANNOT_USE_MY_TELEPORTS_DURING_A_DUEL(2350),
	
	YOU_CANNOT_USE_MY_TELEPORTS_WHILE_FLYING(2351),
	
	YOU_CANNOT_USE_MY_TELEPORTS_WHILE_PARTICIPATING_IN_AN_OLYMPIAD_MATCH(2352),
	
	YOU_CANNOT_USE_MY_TELEPORTS_WHILE_YOU_ARE_IN_A_PETRIFIED_OR_PARALYZED_STATE(2353),
	
	YOU_CANNOT_USE_MY_TELEPORTS_WHILE_YOU_ARE_DEAD(2354),
	
	YOU_CANNOT_USE_MY_TELEPORTS_IN_THIS_AREA(2355),
	
	YOU_CANNOT_USE_MY_TELEPORTS_UNDERWATER(2356),
	
	YOU_CANNOT_USE_MY_TELEPORTS_IN_AN_INSTANT_ZONE(2357),
	
	YOU_HAVE_NO_SPACE_TO_SAVE_THE_TELEPORT_LOCATION(2358),
	
	YOU_CANNOT_TELEPORT_BECAUSE_YOU_DO_NOT_HAVE_A_TELEPORT_ITEM(2359),
	
	RESURRECTION_WILL_TAKE_PLACE_IN_THE_WAITING_ROOM_AFTER_S1_SECONDS(2370),
	
	C1_WAS_REPORTED_AS_A_BOT(2371),
	
	END_MATCH(2374),
	
	YOU_CANNOT_RECEIVE_A_VITAMIN_ITEM_DURING_AN_EXCHANGE(2376),
	
	YOU_CANNOT_REPORT_A_CHARACTER_WHO_IS_IN_A_PEACE_ZONE_OR_A_BATTLEGROUND(2377),
	
	YOU_CANNOT_REPORT_WHEN_A_CLAN_WAR_HAS_BEEN_DECLARED(2378),
	
	YOU_CANNOT_REPORT_A_CHARACTER_WHO_HAS_NOT_ACQUIRED_ANY_XP_AFTER_CONNECTING(2379),
	
	YOU_CANNOT_REPORT_THIS_PERSON_AGAIN_AT_THIS_TIME(2380),
	
	A_PARTY_CANNOT_BE_FORMED_IN_THIS_AREA(2388),
	
	YOU_HAVE_USED_THE_FEATHER_OF_BLESSING_TO_RESURRECT(2391),
	
	THAT_PET_SERVITOR_SKILL_CANNOT_BE_USED_BECAUSE_IT_IS_RECHARGING(2396),
	
	INSTANT_ZONE_CURRENTLY_IN_USE_S1(2400),
	
	CLAN_LORD_C2_WHO_LEADS_CLAN_S1_HAS_BEEN_DECLARED_THE_LORD_OF_THE_S3_TERRITORY(2401),
	
	THE_TERRITORY_WAR_REQUEST_PERIOD_HAS_ENDED(2402),
	
	THE_TERRITORY_WAR_BEGINS_IN_10_MINUTES(2403),
	
	THE_TERRITORY_WAR_BEGINS_IN_5_MINUTES(2404),
	
	THE_TERRITORY_WAR_BEGINS_IN_1_MINUTE(2405),
	
	YOU_ARE_CURRENTLY_REGISTERED_FOR_A_3_VS_3_CLASS_IRRELEVANT_TEAM_MATCH(2408),
	
	THE_NUMBER_OF_MY_TELEPORTS_SLOTS_HAS_BEEN_INCREASED(2409),
	
	YOU_CANNOT_USE_MY_TELEPORTS_TO_REACH_THIS_AREA(2410),
	
	THE_COLLECTION_HAS_FAILED(2424),
	
	THE_RED_TEAM_IS_VICTORIOUS(2427),
	
	THE_BLUE_TEAM_IS_VICTORIOUS(2428),
	
	C1_IS_ALREADY_REGISTERED_ON_THE_WAITING_LIST_FOR_THE_3_VS_3_CLASS_IRRELEVANT_TEAM_MATCH(2440),
	
	ONLY_A_PARTY_LEADER_CAN_REQUEST_A_TEAM_MATCH(2441),
	
	THE_REQUEST_CANNOT_BE_MADE_BECAUSE_THE_REQUIREMENTS_HAVE_NOT_BEEN_MET(2442),
	
	THE_BATTLEFIELD_CHANNEL_HAS_BEEN_ACTIVATED(2445),
	
	THE_BATTLEFIELD_CHANNEL_HAS_BEEN_DEACTIVATED(2446),
	
	FIVE_YEARS_HAVE_PASSED_SINCE_THIS_CHARACTERS_CREATION(2447),
	
	YOUR_BIRTHDAY_GIFT_HAS_ARRIVED(2448),
	
	THERE_ARE_S1_DAYS_UNTIL_YOUR_CHARACTERS_BIRTHDAY(2449),
	
	C1S_BIRTHDAY_IS_S3S4S2(2450),
	
	YOUR_CLOAK_HAS_BEEN_UNEQUIPPED_BECAUSE_YOUR_ARMOR_SET_IS_NO_LONGER_COMPLETE(2451),
	
	THE_CLOAK_CANNOT_BE_EQUIPPED_BECAUSE_YOUR_ARMOR_SET_IS_NOT_COMPLETE(2453),
	
	IN_ORDER_TO_ACQUIRE_AN_AIRSHIP_THE_CLANS_LEVEL_MUST_BE_LEVEL_5_OR_HIGHER(2456),
	
	AN_AIRSHIP_CANNOT_BE_SUMMONED_BECAUSE_EITHER_YOU_HAVE_NOT_REGISTERED_YOUR_AIRSHIP_LICENSE_OR_THE_AIRSHIP_HAS_NOT_YET_BEEN_SUMMONED(2457),
	
	YOUR_CLANS_AIRSHIP_IS_ALREADY_BEING_USED_BY_ANOTHER_CLAN_MEMBER(2458),
	
	THE_AIRSHIP_SUMMON_LICENSE_HAS_ALREADY_BEEN_ACQUIRED(2459),
	
	THE_CLAN_OWNED_AIRSHIP_ALREADY_EXISTS(2460),
	
	AN_AIRSHIP_CANNOT_BE_SUMMONED_BECAUSE_YOU_DONT_HAVE_ENOUGH_S1(2462),
	
	THE_AIRSHIPS_FUEL_EP_WILL_SOON_RUN_OUT(2463),
	
	THE_AIRSHIPS_FUEL_EP_HAS_RUN_OUT(2464),
	
	A_PET_ON_AUXILIARY_MODE_CANNOT_USE_SKILLS(2466),
	
	YOU_HAVE_USED_A_REPORT_POINT_ON_C1_YOU_HAVE_S2_POINTS_REMAINING_ON_THIS_ACCOUNT(2468),
	
	YOU_HAVE_USED_ALL_AVAILABLE_POINTS_POINTS_ARE_RESET_EVERYDAY_AT_NOON(2469),
	
	THIS_CHARACTER_CANNOT_MAKE_A_REPORT_YOU_CANNOT_MAKE_A_REPORT_WHILE_LOCATED_INSIDE_A_PEACE_ZONE_OR_A_BATTLEGROUND_WHILE_YOU_ARE_AN_OPPOSING_CLAN_MEMBER_DURING_A_CLAN_WAR_OR_WHILE_PARTICIPATING_IN_THE_OLYMPIAD(2470),
	
	THIS_CHARACTER_CANNOT_MAKE_A_REPORT_THE_TARGET_HAS_ALREADY_BEEN_REPORTED_BY_EITHER_YOUR_CLAN_OR_ALLIANCE_OR_HAS_ALREADY_BEEN_REPORTED_FROM_YOUR_CURRENT_IP(2471),
	
	YOU_HAVE_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_SO_YOUR_CHATTING_WILL_BE_BLOCKED_FOR_10_MINUTES(2473),
	
	YOU_HAVE_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_SO_YOUR_PARTY_PARTICIPATION_WILL_BE_BLOCKED_FOR_60_MINUTES(2474),
	
	YOU_HAVE_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_SO_YOUR_ACTIONS_WILL_BE_RESTRICTED_FOR_120_MINUTES(2477),
	
	YOU_HAVE_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_SO_YOUR_ACTIONS_WILL_BE_RESTRICTED_FOR_180_MINUTES(2478),
	
	YOU_HAVE_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_SO_MOVEMENT_IS_PROHIBITED_FOR_120_MINUTES(2480),
	
	C1_HAS_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_AND_CANNOT_JOIN_A_PARTY(2482),
	
	YOU_HAVE_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_SO_PARTICIPATING_IN_A_PARTY_IS_NOT_ALLOWED(2484),
	
	YOUR_SHIP_CANNOT_TELEPORT_BECAUSE_IT_DOES_NOT_HAVE_ENOUGH_FUEL_FOR_THE_TRIP(2491),
	
	THE_S1_WARD_HAS_BEEN_DESTROYED_C2_NOW_HAS_THE_TERRITORY_WARD(2750),
	
	THE_CHARACTER_THAT_ACQUIRED_S1S_WARD_HAS_BEEN_KILLED(2751),
	
	YOU_CANNOT_ENTER_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2706),
	
	YOU_CANNOT_REGISTER_WHILE_IN_POSSESSION_OF_A_CURSED_WEAPON(2708),
	
	APPLICANTS_FOR_THE_OLYMPIAD_UNDERGROUND_COLISEUM_OR_KRATEIS_CUBE_MATCHES_CANNOT_REGISTER(2709),
	
	YOU_CANNOT_BOARD_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2727),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_TRANSFORMED(2729),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_YOU_ARE_PETRIFIED(2730),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHEN_YOU_ARE_DEAD(2731),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_FISHING(2732),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_BATTLE(2733),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_DUEL(2734),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_IN_A_SITTING_POSITION(2735),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_USING_A_SKILL(2736),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_A_CURSED_WEAPON_IS_EQUIPPED(2737),
	
	YOU_CANNOT_CONTROL_THE_HELM_WHILE_HOLDING_A_FLAG(2738),
	
	YOU_CANNOT_CONTROL_THE_HELM_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2739),
	
	THIS_ACTION_IS_PROHIBITED_WHILE_STEERING(2740),
	
	YOU_HAVE_BEEN_REPORTED_AS_AN_ILLEGAL_PROGRAM_USER_AND_CANNOT_REPORT_OTHER_USERS(2748),
	
	THIS_TYPE_OF_ATTACK_IS_PROHIBITED_WHEN_ALLIED_TROOPS_ARE_THE_TARGET(2753),
	
	YOU_CANNOT_BE_SIMULTANEOUSLY_REGISTERED_FOR_PVP_MATCHES_SUCH_AS_THE_OLYMPIAD_UNDERGROUND_COLISEUM_AERIAL_CLEFT_KRATEIS_CUBE_AND_HANDYS_BLOCK_CHECKERS(2754),
	
	ANOTHER_PLAYER_IS_PROBABLY_CONTROLLING_THE_TARGET(2756),
	
	YOU_MUST_TARGET_THE_ONE_YOU_WISH_TO_CONTROL(2761),
	
	YOU_CANNOT_CONTROL_BECAUSE_YOU_ARE_TOO_FAR(2762),
	
	ONLY_THE_ALLIANCE_CHANNEL_LEADER_CAN_ATTEMPT_ENTRY(2765),
	
	YOU_CAN_MAKE_ANOTHER_REPORT_IN_S1MINUTES_YOU_HAVE_S2_POINTS_REMAINING_ON_THIS_ACCOUNT(2774),
	
	THE_EFFECT_OF_TERRITORY_WARD_IS_DISAPPEARING(2776),
	
	THE_AIRSHIP_SUMMON_LICENSE_HAS_BEEN_ENTERED(2777),
	
	YOU_CANNOT_TELEPORT_WHILE_IN_POSSESSION_OF_A_WARD(2778),
	
	C1_HAS_DRAINED_YOU_OF_S2_HP(2787),
	
	MERCENARY_PARTICIPATION_IS_REQUESTED_IN_S1_TERRITORY(2788),
	
	MERCENARY_PARTICIPATION_REQUEST_IS_CANCELLED_IN_S1_TERRITORY(2789),
	
	CLAN_PARTICIPATION_IS_REQUESTED_IN_S1_TERRITORY(2790),
	
	CLAN_PARTICIPATION_REQUEST_IS_CANCELLED_IN_S1_TERRITORY(2791),
	
	YOU_MUST_HAVE_A_MINIMUM_OF_S1_PEOPLE_TO_ENTER_THIS_INSTANT_ZONE(2793),
	
	THE_TERRITORY_WAR_CHANNEL_AND_FUNCTIONS_WILL_NOW_BE_DEACTIVATED(2794),
	
	YOUVE_ALREADY_REQUESTED_A_TERRITORY_WAR_IN_ANOTHER_TERRITORY_ELSEWHERE(2795),
	
	THE_CLAN_WHO_OWNS_THE_TERRITORY_CANNOT_PARTICIPATE_IN_THE_TERRITORY_WAR_AS_MERCENARIES(2796),
	
	IT_IS_NOT_A_TERRITORY_WAR_REGISTRATION_PERIOD_SO_A_REQUEST_CANNOT_BE_MADE_AT_THIS_TIME(2797),
	
	THE_TERRITORY_WAR_WILL_END_IN_S1HOURS(2798),
	
	THE_TERRITORY_WAR_WILL_END_IN_S1MINUTES(2799),
	
	S1_SECONDS_TO_THE_END_OF_TERRITORY_WAR(2900),
	
	YOU_CANNOT_FORCE_ATTACK_A_MEMBER_OF_THE_SAME_TERRITORY(2901),
	
	YOUVE_ACQUIRED_THE_WARD(2902),
	
	TERRITORY_WAR_HAS_BEGUN(2903),
	
	TERRITORY_WAR_HAS_ENDED(2904),
	
	YOUVE_REQUESTED_C1_TO_BE_ON_YOUR_FRIENDS_LIST(2911),
	
	CLAN_S1_HAS_SUCCEEDED_IN_CAPTURING_S2S_TERRITORY_WARD(2913),
	
	THE_TERRITORY_WAR_WILL_BEGIN_IN_20_MINUTES(2914),
	
	THIS_CLAN_MEMBER_CANNOT_WITHDRAW_OR_BE_EXPELLED_WHILE_PARTICIPATING_IN_A_TERRITORY_WAR(2915),
	
	ONLY_CHARACTERS_WHO_ARE_LEVEL_40_OR_ABOVE_WHO_HAVE_COMPLETED_THEIR_SECOND_CLASS_TRANSFER_CAN_REGISTER_IN_A_TERRITORY_WAR(2918),
	
	THE_DISGUISE_SCROLL_CANNOT_BE_USED_BECAUSE_IT_IS_MEANT_FOR_USE_IN_A_DIFFERENT_TERRITORY(2936),
	
	A_TERRITORY_OWNING_CLAN_MEMBER_CANNOT_USE_A_DISGUISE_SCROLL(2937),
	
	THE_DISGUISE_SCROLL_CANNOT_BE_USED_WHILE_YOU_ARE_ENGAGED_IN_A_PRIVATE_STORE_OR_MANUFACTURE_WORKSHOP(2938),
	
	A_DISGUISE_CANNOT_BE_USED_WHEN_YOU_ARE_IN_A_CHAOTIC_STATE(2939),
	
	THE_TERRITORY_WAR_EXCLUSIVE_DISGUISE_AND_TRANSFORMATION_CAN_BE_USED_20_MINUTES_BEFORE_THE_START_OF_THE_TERRITORY_WAR_TO_10_MINUTES_AFTER_ITS_END(2955),
	
	A_CHARACTER_BORN_ON_FEBRUARY_29_WILL_RECEIVE_A_GIFT_ON_FEBRUARY_28(2957),
	
	AN_AGATHION_HAS_ALREADY_BEEN_SUMMONED(2958),
	
	THE_PREVIOUS_MAIL_WAS_FORWARDED_LESS_THAN_1_MINUTE_AGO_AND_THIS_CANNOT_BE_FORWARDED(2969),
	
	YOU_CANNOT_FORWARD_IN_A_NONPEACE_ZONE_LOCATION(2970),
	
	YOU_CANNOT_FORWARD_DURING_AN_EXCHANGE(2971),
	
	YOU_CANNOT_FORWARD_BECAUSE_THE_PRIVATE_SHOP_OR_WORKSHOP_IS_IN_PROGRESS(2972),
	
	YOU_CANNOT_FORWARD_DURING_AN_ITEM_ENHANCEMENT_OR_ATTRIBUTE_ENHANCEMENT(2973),
	
	THE_ITEM_THAT_YOURE_TRYING_TO_SEND_CANNOT_BE_FORWARDED_BECAUSE_IT_ISNT_PROPER(2974),
	
	YOU_CANNOT_FORWARD_BECAUSE_YOU_DONT_HAVE_ENOUGH_ADENA(2975),
	
	YOU_CANNOT_RECEIVE_IN_A_NONPEACE_ZONE_LOCATION(2976),
	
	YOU_CANNOT_RECEIVE_DURING_AN_EXCHANGE(2977),
	
	YOU_CANNOT_RECEIVE_BECAUSE_THE_PRIVATE_SHOP_OR_WORKSHOP_IS_IN_PROGRESS(2978),
	
	YOU_CANNOT_RECEIVE_DURING_AN_ITEM_ENHANCEMENT_OR_ATTRIBUTE_ENHANCEMENT(2979),
	
	YOU_CANNOT_RECEIVE_BECAUSE_YOU_DONT_HAVE_ENOUGH_ADENA(2980),
	
	YOU_COULD_NOT_RECEIVE_BECAUSE_YOUR_INVENTORY_IS_FULL(2981),
	
	YOU_CANNOT_CANCEL_IN_A_NONPEACE_ZONE_LOCATION(2982),
	
	YOU_CANNOT_CANCEL_DURING_AN_EXCHANGE(2983),
	
	YOU_CANNOT_CANCEL_BECAUSE_THE_PRIVATE_SHOP_OR_WORKSHOP_IS_IN_PROGRESS(2984),
	
	YOU_CANNOT_CANCEL_DURING_AN_ITEM_ENHANCEMENT_OR_ATTRIBUTE_ENHANCEMENT(2985),
	
	YOU_COULD_NOT_CANCEL_RECEIPT_BECAUSE_YOUR_INVENTORY_IS_FULL(2988),
	
	THE_COMMAND_CHANNEL_MATCHING_ROOM_WAS_CANCELLED(2994),
	
	YOU_CANNOT_ENTER_THE_COMMAND_CHANNEL_MATCHING_ROOM_BECAUSE_YOU_DO_NOT_MEET_THE_REQUIREMENTS(2996),
	
	YOU_EXITED_FROM_THE_COMMAND_CHANNEL_MATCHING_ROOM(2997),
	
	YOU_WERE_EXPELLED_FROM_THE_COMMAND_CHANNEL_MATCHING_ROOM(2998),
	
	THE_COMMAND_CHANNEL_AFFILIATED_PARTYS_PARTY_MEMBER_CANNOT_USE_THE_MATCHING_SCREEN(2999),
	
	THE_COMMAND_CHANNEL_MATCHING_ROOM_WAS_CREATED(3000),
	
	THE_COMMAND_CHANNEL_MATCHING_ROOM_INFORMATION_WAS_EDITED(3001),
	
	WHEN_THE_RECIPIENT_DOESNT_EXIST_OR_THE_CHARACTER_HAS_BEEN_DELETED_SENDING_MAIL_IS_NOT_POSSIBLE(3002),
	
	C1_ENTERED_THE_COMMAND_CHANNEL_MATCHING_ROOM(3003),
	
	SHYEEDS_ROAR_FILLED_WITH_WRATH_RINGS_THROUGHOUT_THE_STAKATO_NEST(3007),
	
	THE_MAIL_HAS_ARRIVED(3008),
	
	MAIL_SUCCESSFULLY_SENT(3009),
	
	MAIL_SUCCESSFULLY_CANCELLED(3011),
	
	THE_KASHAS_EYE_GIVES_YOU_A_STRANGE_FEELING(3022),
	
	I_CAN_FEEL_THAT_THE_ENERGY_BEING_FLOWN_IN_THE_KASHAS_EYE_IS_GETTING_STRONGER_RAPIDLY(3023),
	
	KASHAS_EYE_PITCHES_AND_TOSSES_LIKE_ITS_ABOUT_TO_EXPLODE(3024),
	
	YOU_CANNOT_USE_THE_SKILL_ENHANCING_FUNCTION_ON_THIS_LEVEL_YOU_CAN_USE_THE_CORRESPONDING_FUNCTION_ON_LEVELS_HIGHER_THAN_76LV_(3026),
	
	YOU_CANNOT_USE_THE_SKILL_ENHANCING_FUNCTION_IN_THIS_CLASS_YOU_CAN_USE_CORRESPONDING_FUNCTION_WHEN_COMPLETING_THE_THIRD_CLASS_CHANGE(3027),
	
	YOU_CANNOT_USE_THE_SKILL_ENHANCING_FUNCTION_IN_THIS_CLASS_YOU_CAN_USE_THE_SKILL_ENHANCING_FUNCTION_UNDER_OFFBATTLE_STATUS_AND_CANNOT_USE_THE_FUNCTION_WHILE_TRANSFORMING_BATTLING_AND_ONBOARD(3028),
	
	S1_ACQUIRED_THE_ATTACHED_ITEM_TO_YOUR_MAIL(3072),
	
	YOU_HAVE_ACQUIRED_S2_S1(3073),
	
	A_USER_CURRENTLY_PARTICIPATING_IN_THE_OLYMPIAD_CANNOT_SEND_PARTY_AND_FRIEND_INVITATIONS(3094),
	
	YOU_ARE_NO_LONGER_PROTECTED_FROM_AGGRESSIVE_MONSTERS(3108),
	
	MAIL_SUCCESSFULLY_RECEIVED(3012),
	
	YOU_CANNOT_SEND_A_MAIL_TO_YOURSELF(3019),
	
	THE_COUPLE_ACTION_WAS_DENIED(3119),
	
	THE_REQUEST_CANNOT_BE_COMPLETED_BECAUSE_THE_TARGET_DOES_NOT_MEET_LOCATION_REQUIREMENTS(3120),
	
	THE_COUPLE_ACTION_WAS_CANCELLED(3121),
	
	THE_SIZE_OF_THE_UPLOADED_SYMBOL_DOES_NOT_MEET_THE_STANDARD_REQUIREMENTS(3122),
	
	C1_IS_ALREADY_PARTICIPATING_IN_A_COUPLE_ACTION_AND_CANNOT_BE_REQUESTED_FOR_ANOTHER_COUPLE_ACTION(3126),
	
	C1_IS_IN_A_CHAOTIC_STATE_AND_CANNOT_BE_REQUESTED_FOR_A_COUPLE_ACTION(3127),
	
	THE_CREST_WAS_SUCCESSFULLY_REGISTERED(3140),
	
	THIS_ITEM_CANNOT_BE_USED_BECAUSE_YOU_ARE_ALREADY_PARTICIPATING_IN_THE_QUEST_THAT_CAN_BE_STARTED_WITH_THIS_ITEM(3145),
	
	YOU_HAVE_REQUESTED_A_COUPLE_ACTION_WITH_C1(3150),
	
	C1_IS_SET_TO_REFUSE_DUEL_REQUESTS_AND_CANNOT_RECEIVE_A_DUEL_REQUEST(3169),
	
	WHEN_YOUR_PETS_HUNGER_GAUGE_IS_AT_0_YOU_CANNOT_USE_YOUR_PET(3212),
	
	YOUR_PET_IS_STARVING_AND_WILL_NOT_OBEY_UNTIL_IT_GETS_ITS_FOOD(3213),
	
	S1_WAS_SUCCESSFULLY_ADDED_TO_YOUR_CONTACT_LIST(3214),
	
	THE_NAME_S1__DOESNT_EXIST(3215),
	
	THE_NAME_ALREADY_EXISTS_ON_THE_ADDED_LIST(3216),
	
	THE_NAME_IS_NOT_CURRENTLY_REGISTERED(3217),
	
	S1_WAS_SUCCESSFULLY_DELETED_FROM_YOUR_CONTACT_LIST(3219),
	
	YOU_CANNOT_ADD_YOUR_OWN_NAME(3221),
	
	THE_MAXIMUM_NUMBER_OF_NAMES_100_HAS_BEEN_REACHED(3222),
	
	THE_MAXIMUM_MATCHES_YOU_CAN_PARTICIPATE_IN_1_WEEK_IS_70(3224),
	
	THE_TOTAL_NUMBER_OF_MATCHES_THAT_CAN_BE_ENTERED_IN_1_WEEK_IS_60_CLASS_IRRELEVANT_INDIVIDUAL_MATCHES_30_SPECIFIC_MATCHES_AND_10_TEAM_MATCHES(3225),
	
	YOU_CANNOT_MOVE_WHILE_SPEAKING_TO_AN_NPC(3226),
	
	MP_BECAME_0_AND_THE_ARCANE_SHIELD_IS_DISAPPEARING(3256),
	
	YOU_HAVE_ACQUIRED_S1_EXP_BONUS_S2_AND_S3_SP_BONUS_S4(3259),
	
	YOU_HAVE_S1_MATCHES_REMAINING_THAT_YOU_CAN_PARTICIPATE_IN_THIS_WEEK_S2_1_VS_1_CLASS_MATCHES_S3_1_VS_1_MATCHES__S4_3_VS_3_TEAM_MATCHES(3261),
	
	THERE_ARE_S2_SECONDS_REMAINING_FOR_S1S_REUSE_TIME(3263),
	
	THERE_ARE_S2_MINUTES_S3_SECONDS_REMAINING_FOR_S1S_REUSE_TIME(3264),
	
	THERE_ARE_S2_HOURS_S3_MINUTES_S4_SECONDS_REMAINING_FOR_S1S_REUSE_TIME(3265),
	
	C1_IS_SET_TO_REFUSE_COUPLE_ACTIONS_AND_CANNOT_BE_REQUESTED_FOR_A_COUPLE_ACTION(3164),
	
	ARCANE_SHIELD_DECREASED_YOUR_MP_BY_S1_INSTEAD_OF_HP(3255),
	
	THE_ANGEL_NEVIT_HAS_BLESSED_YOU_FROM_ABOVE_YOU_ARE_IMBUED_WITH_FULL_VITALITY_AS_WELL_AS_A_VITALITY_REPLENISHING_EFFECT(3266),
	
	YOU_ARE_STARTING_TO_FEEL_THE_EFFECTS_OF_NEVITS_BLESSING(3267),
	
	YOU_ARE_FURTHER_INFUSED_WITH_THE_BLESSINGS_OF_NEVIT_CONTINUE_TO_BATTLE_EVIL_WHEREVER_IT_MAY_LURK(3268),
	
	NEVITS_BLESSING_SHINES_STRONGLY_FROM_ABOVE_YOU_CAN_ALMOST_SEE_HIS_DIVINE_AURA(3269),
	
	NEVITS_BLESSING_HAS_ENDED_CONTINUE_YOUR_JOURNEY_AND_YOU_WILL_SURELY_MEET_HIS_FAVOR_AGAIN_SOMETIME_SOON(3275),
	
	SUBCLASS_S1_HAS_BEEN_UPGRADED_TO_DUEL_CLASS_S2_CONGRATULATIONS(3279),
	
	THE_NUMBER_OF_GRADUATES_OF_THE_CLAN_ACADEMY_IS_S1_S2_BONUS_POINTS_HAVE_BEEN_ADDED_TO_YOUR_CLAN_REPUTATION(3299),
	
	ENTRY_TO_MEMO_IS_COMPLETE(3332),
	
	REGISTRATION_IS_NOT_AVAILABLE_BECAUSE_THE_CORRESPONDING_ITEM_DOES_NOT_EXIST(3361),
	
	THE_ITEM_CANNOT_BE_REGISTERED_BECAUSE_REQUIREMENTS_ARE_NOT_MET(3363),
	
	NOT_ENOUGH_ADENA_FOR_REGISTER_THIS_ITEM(3364),
	
	FAILED_TO_REGISTER_ITEM(3365),
	
	CURRENTLY_THERE_ARE_NO_REGISTERED_ITEMS(3369),
	
	ITEM_PURCHASE_IS_NOT_AVAILABLE_BECAUSE_THE_CORRESPONDING_ITEM_DOES_NOT_EXIST(3370),
	
	ITEM_PURCHASE_HAS_FAILED(3371),
	
	YOU_CANNOT_MOVE_WHILE_DEAD(3392),
	
	YOU_CANNOT_MOVE_DURING_COMBAT(3393),
	
	YOU_CANNOT_MOVE_WHILE_IN_A_CHAOTIC_STATE(3404),
	
	S1_ALREADY_GRADUATED_FROM_A_CLAN_ACADEMY_THEREFORE_REJOINING_IS_NOT_ALLOWED(3420),
	
	CONGRATULATIONS_YOU_WILL_NOW_GRADUATE_FROM_THE_CLAN_ACADEMY_AND_LEAVE_YOUR_CURRENT_CLAN_AS_A_GRADUATE_OF_THE_ACADEMY_YOU_CAN_IMMEDIATELY_JOIN_A_CLAN_AS_A_REGULAR_MEMBER_WITHOUT_BEING_SUBJECT_TO_ANY_PENALTIES(3430),
	
	STOPPED_SEARCHING_THE_PARTY(3453),
	
	C1_USED_S3_ON_C2(3463),
	
	YOUR_BID_FOR_THE_PROVISIONAL_CLAN_HALL_WON(3465),
	
	YOUR_BID_FOR_THE_PROVISIONAL_CLAN_HALL_LOST(3466),
	
	CLAN_LEVEL_REQUIREMENTS_FOR_BIDDING_ARE_NOT_MET(3467),
	
	YOU_MADE_A_BID_AT_S1(3468),
	
	YOU_ALREADY_MADE_A_BID_FOR_THE_PROVISIONAL_CLAN_HALL(3469),
	
	IT_IS_NOT_THE_BIDDING_PERIOD_FOR_THE_PROVISIONAL_CLAN_HALL(3470),
	
	YOU_CANNOT_MAKE_A_BID_BECAUSE_YOU_DONT_BELONG_TO_A_CLAN(3471),
	
	YOU_MUST_HAVE_RIGHTS_TO_A_CLAN_HALL_AUCTION_IN_ORDER_TO_MAKE_A_BID_FOR_PROVISIONAL_CLAN_HALL(3472),
	
	ITEMS_THAT_CANNOT_BE_EXCHANGEDDROPPEDUSE_A_PRIVATE_STORE_OR_THAT_ARE_FOR_A_LIMITED_PERIODAUGMENTING_CANNOT_BE_REGISTERED(3480),
	
	IF_THE_WEIGHT_IS_80_OR_MORE_AND_THE_INVENTORY_NUMBER_IS_90_OR_MORE_PURCHASECANCELLATION_IS_NOT_POSSIBLE(3481),
	
	ITEM_REGISTER_WAS_SUCCESSFUL(3484),
	
	CANCELLATION_OF_SALE_FOR_THE_ITEM_IS_SUCCESSFUL(3485),
	
	THE_ITEM_YOU_REGISTERED_HAS_BEEN_SOLD(3490),
	
	S1_HAS_BEEN_SOLD(3491),
	
	THE_REGISTRATION_PERIOD_FOR_THE_ITEM_YOU_REGISTERED_HAS_EXPIRED(3492),
	
	THE_AUCTION_HOUSE_REGISTRATION_PERIOD_HAS_EXPIRED_AND_THE_CORRESPONDING_ITEM_IS_BEING_FORWARDED(3493),
	
	YOU_CANNOT_RECEIVE_A_SYMBOL_BECAUSE_YOU_ARE_BELOW_THE_REQUIRED_LEVEL(3498),
	
	YOU_CANNOT_RECEIVE_A_SYMBOL_BECAUSE_YOU_DONT_HAVE_ENOUGH_ADENA(3499),
	
	YOU_CANNOT_RECEIVE_A_SYMBOL_BECAUSE_YOU_DONT_HAVE_ENOUGH_DYE(3500),
	
	YOU_CANNOT_RECEIVE_A_SYMBOL_BECAUSE_YOU_DONT_MEET_THE_CLASS_REQUIREMENTS(3501),
	
	A_REPLACEMENT_PLAYER_FOR_C1_HAS_BEEN_FOUND_AND_AN_INVITATION_IS_SENT(3511),
	
	THE_PLAYER_WHO_WAS_INVITED_REJECTED_THE_INVITATION_PLEASE_REGISTER_AGAIN(3512),
	
	WAITING_LIST_REGISTRATION_IS_CANCELLED_BECAUSE_THE_CURSED_SWORD_IS_BEING_USED_OR_THE_STATUS_IS_IN_A_CHAOTIC_STATE(3513),
	
	WAITING_LIST_REGISTRATION_IS_CANCELLED_BECAUSE_YOU_ARE_IN_A_DUEL(3514),
	
	WAITING_LIST_REGISTRATION_IS_CANCELLED_BECAUSE_YOU_ARE_CURRENTLY_PARTICIPATING_IN_OLYMPIAD(3515),
	
	WAITING_LIST_REGISTRATION_IS_CANCELLED_BECAUSE_YOU_ARE_CURRENTLY_PARTICIPATING_IN_BLOCK_CHECKERCOLISEUMKRATEIS_CUBE(3516),
	
	YOU_CANNOT_REGISTER_IN_THE_WAITING_LIST_WHILE_BEING_INSIDE_OF_A_BATTLEGROUND_CASTLE_SIEGEFORTRESS_SIEGETERRITORY_WAR(3517),
	
	WAITING_LIST_REGISTRATION_IS_NOT_ALLOWED_WHILE_THE_CURSED_SWORD_IS_BEING_USED_OR_THE_STATUS_IS_IN_A_CHAOTIC_STATE(3518),
	
	YOU_CANNOT_REGISTER_IN_THE_WAITING_LIST_DURING_A_DUEL(3519),
	
	YOU_CANNOT_REGISTER_IN_THE_WAITING_LIST_WHILE_PARTICIPATING_IN_OLYMPIAD(3520),
	
	YOU_CANNOT_REGISTER_IN_THE_WAITING_LIST_WHILE_PARTICIPATING_IN_BLOCK_CHECKERCOLISEUMKRATEIS_CUBE(3521),
	
	YOU_CANNOT_REGISTER_IN_THE_WAITING_LIST_WHILE_BEING_INSIDE_OF_A_BATTLEGROUND_CASTLE_SIEGEFORTRESS_SIEGETERRITORY_WAR2(3522),
	
	LOOKING_FOR_A_PLAYER_WHO_WILL_REPLACE_THE_SELECTED_PARTY_MEMBER(3523),
	
	VITALITY_EFFECT_IS_APPLIED_THERES_S1_VITALITY_EFFECT_LEFT_THAT_MAY_BE_APPLIED_UNTIL_THE_NEXT_CYCLE(3528),
	
	YOU_HAVE_SUCCESSFULLY_PURCHASED_S2_OF_S1(3530),
	
	YOU_ARE_REGISTERED_ON_THE_WAITING_LIST(3452),
	
	YOU_CAN_NOT_CHANGE_CLASS_DUE_TO_DISRUPTION_OF_THE_IDENTIFICATION(3574),
	
	YOU_MAY_NOT_USE_SAYUNE_WHILE_PET_OR_SUMMONED_PET_IS_OUT(3625),
	
	THE_CORRESPONDING_WORK_CANNOT_BE_PROCEEDED_BECAUSE_THE_INVENTORY_WEIGHTQUANTITY_LIMIT_HAS_BEEN_EXCEEDED(3646),
	
	YOU_CANNOT_USE_SKILLS_IN_THE_CORRESPONDING_REGION(3648),
	
	YOU_CANNOT_AWAKEN_DUE_TO_WEIGHT_LIMITS_PLEASE_TRY_AWAKEN_AGAIN_AFTER_INCREASING_THE_ALLOWED_WEIGHT_BY_ORGANIZING_THE_INVENTORY(3652),
	
	YOU_CANNOT_USE_SAYUNE_WHILE_IN_A_CHAOTIC_STATE(3654),
	
	YOU_CANNOT_AWAKEN_WHILE_YOURE_TRANSFORMED_OR_RIDING(3655),
	
	YOU_CAN_NOT_CHANGE_THE_ATTRIBUTE_WHILE_OPERATING_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP(3659),
	
	UNABLE_TO_CHANCE_THE_ATTRIBUTE(3661),
	
	FIRST__SELECT_THE_ATTRIBUTE_YOU_ARE_GOING_TO_CHANGE(3667),
	
	IN_THE_ITEM_S1_ATTRIBUTE_S2_SUCCESSFULLY_CHANGED_TO_S3(3668),
	
	THE_ITEM_FOR_CHANGING_AN_ATTRIBUTE_DOES_NOT_EXIST(3669),
	
	YOU_CAN_NOT_CHANGE_CLASS_IN_TRANSFORMATION(3677),
	
	THIS_TERRITORY_CAN_NOT_CHANGE_CLASS(3684),
	
	PLUNDER_SKILL_HAS_BEEN_ALREADY_USED_ON_THIS_TARGET(3712),
	
	THE_CHARACTER_AND_ITEM_RECIPE_LEVELS_DO_NOT_MATCH_SO_IT_CANNOT_BE_USED_NORMALLY(3729),
	
	YOU_ARE_NOW_ON_THE_WAITING_LIST(3732),
	
	CYCLE_S1_OF_THE_CEREMONY_OF_CHAOS_HAS_BEGUN(3730),
	
	CYCLE_S1_OF_THE_CEREMONY_OF_CHAOS_HAS_ENDED(3731),
	
	ONLY_CHARACTERS_LEVEL_76_OR_ABOVE_MAY_PARTICIPATE_IN_THE_TOURNAMENT(3733),
	
	YOU_WILL_BE_MOVED_TO_THE_ARENA_IN_S1_SECONDS(3737),
	
	YOU_CANNOT_CHAT_IN_THE_CEREMONY_OF_CHAOS(3741),
	
	YOU_CANNOT_OPEN_A_PRIVATE_STORE_OR_WORKSHOP_IN_THE_CEREMONY_OF_CHAOS(3742),
	
	IN_S1_SECONDS_YOU_WILL_BE_MOVED_TO_WHERE_YOU_WERE_BEFORE_PARTICIPATING_IN_THE_CEREMONY_OF_CHAOS(3749),
	
	YOU_ARE_ON_THE_WAITING_LIST_FOR_THE_CEREMONY_OF_CHAOS(3777),
	
	REGISTRATION_FOR_THE_CEREMONY_OF_CHAOS_HAS_BEGUN(3781),
	
	REGISTRATION_FOR_THE_CEREMONY_OF_CHAOS_HAS_ENDED(3782),
	
	THE_CEREMONY_OF_CHAOS_IS_NOT_CURRENTLY_OPEN(3784),
	
	YOU_CANNOT_INVITE_A_FRIEND_OR_PARTY_WHILE_PARTICIPATING_IN_THE_CEREMONY_OF_CHAOS(3789),
	
	YOU_HAVE_OBTAINED_THE_FIRST_ENERGY_OF_DESTRUCTION_YOU_CAN_OBTAIN_UP_TO_2_OF_THESE_A_DAY_AND_CAN_BEGIN_OBTAINING_THEM_AGAIN_AT_630AM_EVERY_DAY(3791),
	
	YOU_HAVE_OBTAINED_THE_SECOND_ENERGY_OF_DESTRUCTION_YOU_CAN_OBTAIN_UP_TO_2_OF_THESE_A_DAY_AND_CAN_BEGIN_OBTAINING_THEM_AGAIN_AT_630AM_EVERY_DAY(3792),
	
	YOU_HAVE_OBTAINED_S1_BATTLE_MARKS_DURING_THIS_ROUND_OF_THE_CEREMONY_OF_CHAOS(3794),
	
	A_VICTOR_HAD_BEEN_NAMED_IN_THE_CEREMONY_OF_CHAOS(3795),
	
	CURRENT_LOCATION_S1_S2_S3_INSIDE_THE_CEREMONY_OF_CHAOS(3796),
	
	BECAUSE_C1_WAS_KILLED_BY_A_CLAN_MEMBER_OF_S2_CLAN_FAME_POINTS_DECREASED_BY_1(3811),
	
	BECAUSE_A_CLAN_MEMBER_OF_S1_WAS_KILLED_BY_C2_CLAN_FAME_POINTS_INCREASED_BY_1(3812),
	
	YOU_CANNOT_PARTICIPATE_IN_THE_CEREMONY_OF_CHAOS_AS_A_FLYING_TRANSFORMED_OBJECT(3853),
	
	ONLY_THE_CLAN_LEADER_OR_SOMEONE_WITH_RANK_MANAGEMENT_AUTHORITY_MAY_REGISTER_THE_CLAN(4031),
	
	YOU_MAY_APPLY_FOR_ENTRY_AFTER_S1_MINUTES_DUE_TO_CANCELLING_YOUR_APPLICATION(4038),
	
	ENTRY_APPLICATION_COMPLETE_USE_ENTRY_APPLICATION_INFO_TO_CHECK_OR_CANCEL_YOUR_APPLICATION(4039),
	
	ENTRY_APPLICATION_CANCELLED_YOU_MAY_APPLY_TO_A_NEW_CLAN_AFTER_5_MINUTES(4040),
	
	ENTERED_INTO_WAITING_LIST_NAME_IS_AUTOMATICALLY_DELETED_AFTER_30_DAYS_IF_DELETE_FROM_WAITING_LIST_IS_USED_YOU_CANNOT_ENTER_NAMES_INTO_THE_WAITING_LIST_FOR_5_MINUTES(4043),
	
	YOU_CANNOT_USE_THE_S1_SKILL_DUE_TO_INSUFFICIENT_SUMMON_POINTS(4085),
	
	THIS_QUEST_CANNOT_BE_DELETED(4091),
	
	PLAYERS_CAN_SHOUT_AFTER_LV_S1(4104),
	
	PLAYERS_CAN_USE_TRADE_CHAT_AFTER_LV_S1(4105),
	
	PLAYERS_CAN_USE_GENERAL_CHAT_AFTER_LV_S1(4106),
	
	PLAYERS_CAN_RESPOND_TO_A_WHISPER_BUT_CANNOT_INITIATE_A_WHISPER_UNTIL_LV_S1(4107),
	
	YOU_CANNOT_USE_THE_BEAUTY_SHOP_WHILE_REGISTERED_IN_THE_CEREMONY_OF_CHAOS(4126),
	
	YOU_CANNOT_USE_THE_BEAUTY_SHOP_WHILE_REGISTERED_IN_THE_OLYMPIAD(4127),
	
	ADENA_DISTRIBUTION_HAS_STARTED(4150),
	
	ADENA_DISTRIBUTION_HAS_BEEN_CANCELLED(4151),
	
	YOU_CANNOT_PROCEED_AS_YOU_ARE_NOT_IN_AN_ALLIANCE_OR_PARTY(4154),
	
	YOU_CANNOT_PROCEED_AS_YOU_ARE_NOT_A_PARTY_LEADER(4156),
	
	YOU_CANNOT_PROCEED_AS_THERE_IS_INSUFFICIENT_ADENA(4157),
	
	HAIR_ACCESSORIES_WILL_NO_LONGER_BE_DISPLAYED(4167),
	
	HAIR_ACCESSORIES_WILL_BE_DISPLAYED_FROM_NOW_ON(4168),
	
	POINT_CONVERSION_HAS_FAILED_PLEASE_TRY_AGAIN(4184),
	
	YOU_CANNOT_ACQUIRE_ANY_MORE_ABILITY_POINTS(4185),
	
	YOU_NEED_S1_SP_TO_CONVERT_TO1_ABILITY_POINT(4186),
	
	THE_SELECTED_ABILITY_WILL_BE_ACQUIRED(4187),
	
	FAILED_TO_ACQUIRE_ABILITY_PLEASE_TRY_AGAIN(4190),
	
	S1_ADENA_WILL_BE_CONSUMED_AND_SPECIAL_POINTS_WILL_BE_RESET(4191),
	
	ABILITIES_CAN_BE_USED_BY_NOBLESSE_LV_99_OR_ABOVE(4195),
	
	PLEASE_EQUIP_THE_HAIR_ACCESSORY_AND_TRY_AGAIN(4199),
	
	YOU_CONSUMED_S1_RAID_POINTS(4209),
	
	YOU_HAVE_REACHED_THE_MAXIMUM_AMOUNT_OF_RAID_POINTS_AND_CAN_ACQUIRE_NO_MORE(4210),
	
	NOT_ENOUGH_RAID_POINTS(4211),
	
	YOU_CANNOT_PARTICIPATE_IN_THE_CEREMONY_OF_CHAOS_WHILE_FISHING(4215),
	
	YOU_CANNOT_PARTICIPATE_IN_THE_OLYMPIAD_WHILE_FISHING(4216),
	
	YOU_CANNOT_DO_THAT_WHILE_IN_A_PRIVATE_STORE_OR_PRIVATE_WORKSHOP(4217),
	
	THIS_IS_NOT_A_VALID_COMBINATION(4221),
	
	YOU_CAN_USE_THE_WORLD_CHAT_S1_TIMES(4238),
	
	TODAY_YOU_REACHED_THE_LIMIT_OF_USE_OF_THE_WORLD_CHAT__RESET_OF_THE_WORLD_USE_CHAT_IS_DONE_DAILY_AT_6_30_AM(4239),
	
	YOU_CAN_USE_THE_WORLD_CHAT_WITH_S1_LEVEL(4240),
	
	USING_A_SCROLL_OF_ESCAPE_CAN_HELP_YOU_SPEED_ALONG_YOUR_QUEST(4243),
	
	LADY_LUCK_SMILES_UPON_YOU(4244),
	
	EVADED_KILLING_BLOW_LADY_LUCK_WATCHES_OVER_YOU(4245),
	
	YOU_CANNOT_USE_ALCHEMY_DURING_BATTLE(4270),
	
	YOU_CANNOT_USE_ALCHEMY_WHILE_TRADING_OR_USING_A_PRIVATE_STORE_OR_SHOP(4280),
	
	YOU_CANNOT_USE_ALCHEMY_WHILE_DEAD(4281),
	
	YOU_CANNOT_USE_ALCHEMY_WHILE_IMMOBILE(4282),
	
	YOU_CANNOT_CHANGE_YOUR_SUBCLASS_WHILE_REGISTERED_IN_THE_CEREMONY_OF_CHAOS(4299),
	
	YOU_CAN_ONLY_FUSH_DURING_THE_PAID_PERIOD(4303),

	YOU_CAN_REDEEM_YOUR_REWARD_S1_MINUTES_AFTER_LOGGING_IN_S2_MINUTES_LEFT(4321),

	YOU_CAN_REDEEM_YOUR_REWARD_NOW(4322),

	THE_TRADE_WAS_SUCCESSFUL(4358),

	CANNOT_SHOW_BECAUSE_THE_CONDITIONS_ARE_NOT_MET(4361),

	YOU_CANNOT_JOIN_A_CLAN_WHILE_YOU_ARE_IN_THE_TRAINING_CAMP(4371),

	CANNOT_ENTER_SOME_USERS_MAY_NOT_YET_BE_SEATED(4393),

	ONLY_LEVEL_34_CLANS_CAN_BE_REGISTERED_IN_A_CASTLE_SIEGE(4397),
	
	THE_SKILL_HAS_BEEN_CANCELED_BECAUSE_YOU_HAVE_INSUFFICIENT_ENERGY(6042),
	
	YOUR_ENERGY_CANNOT_BE_REPLENISHED_BECAUSE_CONDITIONS_ARE_NOT_MET(6043),
	
	ENERGY_S1_REPLENISHED(6044),
	
	THE_PREMIUM_ITEM_FOR_THIS_ACCOUNT_WAS_PROVIDED_IF_THE_PREMIUM_ACCOUNT_IS_TERMINATED_THIS_ITEM_WILL_BE_DELETED(6046),
	
	THE_PREMIUM_ITEM_CANNOT_BE_RECEIVED_BECAUSE_THE_INVENTORY_WEIGHTQUANTITY_LIMIT_HAS_BEEN_EXCEEDED(6047),
	
	THE_PREMIUM_ACCOUNT_HAS_BEEN_TERMINATED_THE_PROVIDED_PREMIUM_ITEM_WAS_DELETED(6048),
	
	YOU_CANNOT_USE_THIS_SYSTEM_DURING_TRADING_PRIVATE_STORE_AND_WORKSHOP_SETUP(6083),
	
	WEAPON_APPEARANCE_MODIFICATION_OR_RESTORATION_IS_IN_PROGRESS_PLEASE_TRY_AGAIN_AFTER_COMPLETING_THIS_TASK(6084),
	
	THIS_ITEM_CANNOT_BE_MODIFIED_OR_RESTORED(6092),
	
	THIS_ITEM_DOES_NOT_MEET_REQUIREMENTS(6094),
	
	PLEASE_SELECT_AN_ITEM_TO_CHANGE(6096),
	
	YOU_CANNOT_MODIFY_AS_YOU_DO_NOT_HAVE_ENOUGH_ADENA(6099),
	
	YOU_HAVE_SPENT_S1_ON_A_SUCCESSFUL_APPEARANCE_MODIFICATION(6100),
	
	ITEM_GRADES_DO_NOT_MATCH(6101),
	
	YOU_CANNOT_EXTRACT_FROM_ITEMS_THAT_ARE_HIGHERGRADE_THAN_ITEMS_TO_BE_MODIFIED(6102),
	
	YOU_CANNOT_MODIFY_OR_RESTORE_NOGRADE_ITEMS(6103),
	
	WEAPONS_ONLY(6104),
	
	ARMOR_ONLY(6105),
	
	YOU_CANNOT_EXTRACT_FROM_A_MODIFIED_ITEM(6106),
	
	THE_NUMBER_OF_VITALITY_EFFECTS_USABLE_DURING_THIS_PERIOD_HAS_INCREASED_BY_S1_YOU_CAN_CURRENTLY_USE_S2_VITALITY_ITEMS(6111),
	
	YOU_HAVE_ACQUIRED_A_CLAN_HALL_OF_HIGHER_VALUE_THAN_THE_PROVISIONAL_CLAN_HALL_THE_PROVISIONAL_CLAN_HALL_OWNERSHIP_WILL_AUTOMATICALLY_BE_FORFEITED(6136),

	YOU_HAVE_COMPLETED_TRAINING_IN_THE_ROYAL_TRAINING_CAMP_AND_OBTAINED_S1_XP_AND_S2_SP(6138),
	
	NOT_ENOUGH_TICKETS(6139),
	
	YOUR_INVENTORY_IS_EITHER_FULL_OR_OVERWEIGHT(6140),
	
	CONGRATULATIONS_C1_HAS_OBTAINED_S2_OF_S3_THROUGH_FORTUNE_READING(6141),
	
	CONGRATULATIONS_C1_HAS_OBTAINED_S2_OF_S3_IN_THE_LUXURY_FORTUNE_READING(6142),

	YOU_CANNOT_RECEIVE_REWARDS_FOR_TRAINING_IF_YOU_HAVE_TRAINED_FOR_LESS_THAN_1_MINUTE(6154),

	YOU_CANNOT_TAKE_OTHER_ACTION_WHILE_ENTERING_THE_TRAINING_CAMP(6156),

	YOU_CANNOT_REQUEST_TO_A_CHARACTER_WHO_IS_ENTERING_THE_TRAINING_CAMP(6157),
	
	ROUND_S1_OF_FORTUNE_READING_COMPLETE(6158),
	
	ROUND_S1_OF_LUXURY_FORTUNE_READING_COMPLETE(6159),

	CALCULATING_XP_AND_SP_OBTAINED_FROM_TRAINING(6161),

	C1_IS_CURRENTLY_IN_THE_ROYAL_TRAINING_CAMP_AND_CANNOT_PARTICIPATE_IN_THE_OLYMPIAD(6162),

	YOU_CAN_ONLY_BE_REWARDED_AS_THE_CLASS_IN_WHICH_YOU_ENTERED_THE_TRAINING_CAMP(6163),

	ONLY_ONE_CHARACTER_PER_ACCOUNT_MAY_ENTER_AT_ANY_TIME(6166),

	YOU_CANNOT_ENTER_THE_TRAINING_CAMP_WHILE_IN_A_PARTY_OR_USING_THE_AUTOMATIC_REPLACEMENT_SYSTEM(6167),

	YOU_CANNOT_ENTER_THE_TRAINING_CAMP_WITH_A_MOUNT_OR_IN_A_TRANSFORMED_STATE(6168),

	YOU_HAVE_COMPLETED_THE_DAYS_TRAINING(6169),

	LV_S1_OR_ABOVE(6170),

	LV_S1_OR_BELOW(6171),
	
	YOUR_DAY_S1_ATTENDANCE_REWARD_IS_READY_CLICK_ON_THE_REWARDS_ICON(6174),
	
	YOUR_DAY_S1_PC_CAF_ATTENDANCE_REWARD_IS_READY_CLICK_ON_THE_REWARDS_ICON(6175),
	
	YOUVE_RECEIVED_YOUR_ATTENDANCE_REWARD_FOR_DAY_S1_(6176),
	
	YOUVE_RECEIVED_YOUR_PC_CAF_ATTENDANCE_REWARD_FOR_DAY_S1_(6177),
	
	THE_ATTENDANCE_REWARD_CANNOT_BE_RECEIVED_BECAUSE_THE_INVENTORY_WEIGHTQUANTITY_LIMIT_HAS_BEEN_EXCEEDED(6178),
	
	DUE_TO_A_SYSTEM_ERROR_THE_ATTENDANCE_REWARD_CANNOT_BE_RECEIVED_PLEASE_TRY_AGAIN_LATER_BY_GOING_TO_MENU__ATTENDANCE_CHECK(6179),
	
	YOU_CAN_NO_LONGER_RECEIVE_ATTENDANCE_CHECK_REWARDS_(6182),
	
	YOU_CANNOT_BOOKMARK_THIS_LOCATION_BECAUSE_YOU_DO_NOT_HAVE_A_MY_TELEPORT_FLAG(6501),

	YOUR_CLAN_HAS_ACHIEVED_LOGIN_BONUS_LV_S1(6826),

	YOUR_CLAN_HAS_ACHIEVED_HUNTING_BONUS_LV_S1(6827);

	private final L2GameServerPacket _message;
	private final int _id;
	private final byte _size;

	SystemMsg(int i)
	{
		_id = i;

		if(name().contains("S4") || name().contains("C4"))
		{
			_size = 4;
			_message = null;
		}
		else if(name().contains("S3") || name().contains("C3"))
		{
			_size = 3;
			_message = null;
		}
		else if(name().contains("S2") || name().contains("C2"))
		{
			_size = 2;
			_message = null;
		}
		else if(name().contains("S1") || name().contains("C1"))
		{
			_size = 1;
			_message = null;
		}
		else
		{
			_size = 0;
			_message = new SystemMessagePacket(this);
		}
	}

	public int getId()
	{
		return _id;
	}

	public byte size()
	{
		return _size;
	}

	public static SystemMsg valueOf(int id)
	{
		for(SystemMsg m : values())
			if(m.getId() == id)
				return m;

		throw new NoSuchElementException("Not find SystemMsg by id: " + id);
	}

	@Override
	public L2GameServerPacket packet(Player player)
	{
		if(_message == null)
			throw new NoSuchElementException("Running SystemMsg.packet(Player), but message require arguments: " + name());

		return _message;
	}
}